### ISSUE TITLE
`SampleFrame` interacts oddly with GameObject lifecycles

### ISSUE THREAD

**Issue by pelotom** [neuecc/UniRx#107]
Say I have this code, which is similar to one of the examples in the [README](/neuecc/UniRx/blob/master/README.md), but adding a position update:

```c#
var cube = GameObject.CreatePrimitive(PrimitiveType.Cube);

cube.UpdateAsObservable()
    .SampleFrame(30)
    .Subscribe(
        _ => {
            var p = cube.transform.position;
            cube.transform.position = new Vector3(p.x + 0.01f, p.y, p.z);
        },
        e => Debug.LogError("Error! " + e),
        () => Debug.Log("Completed!")
    );

GameObject.Destroy(cube, 3f);
```

Now, without the call to `SampleFrame(20)`, this behaves very predictably, moving the cube slightly along the x-axis every frame for 5 seconds, after which the cube goes away and "Completed!" is printed. However, with the `SampleFrame(20)` call, "Completed!" never gets called. The reason is that even though the cube gets destroyed, the `OnNext` callback is still invoked one last time a few frames later, and the code that attempts to update the cube's transform throws an exception (~~which is silently swallowed~~[*this is fixed on `master`*] and causes the observation to be canceled). We can mitigate this by tying the disposable to the `GameObject` like so:

```c#
cube.UpdateAsObservable()
    .SampleFrame(20)
    .Subscribe(
        _ => {
            var p = cube.transform.position;
            cube.transform.position = new Vector3(p.x + 0.01f, p.y, p.z);
        },
        e => Debug.LogError("Error! " + e),
        () => Debug.Log("Completed!")
    )
    .AddTo(cube); // <-- dispose of this observer as soon as the cube goes away
```

But besides being a confusing extra step after we already initialized the observable from the cube, the semantics have changed; our `OnCompleted` callback never gets called in this case. Is there a better way this could work?

**Comment by neuecc** [comment]
I think you can add `TakeUntilDestory`.

```csharp
var cube = GameObject.CreatePrimitive(PrimitiveType.Cube);

cube.UpdateAsObservable()
    .SampleFrame(30)
    .TakeUntilDestroy(cube) // add line.
    .Subscribe(
       _ =>
        {
            var p = cube.transform.position;
            cube.transform.position = new Vector3(p.x + 0.01f, p.y, p.z);
        },
        e => Debug.LogError("Error! " + e),
        () => Debug.Log("Completed!"));

GameObject.Destroy(cube, 3f);
```

Is this solve your problem?

**Comment by pelotom** [comment]
Reading a bit farther in the README, I see that the way to preserve the `OnCompleted` event is to use `TakeUntilDestroy()` like so:

```c#
cube.UpdateAsObservable()
    .SampleFrame(20)
    .TakeUntilDestroy(cube)
    .Subscribe(
        _ => {
            Debug.Log("Go!");
            var p = cube.transform.position;
            cube.transform.position = new Vector3(p.x + 0.1f, p.y, p.z);
        },
        e => Debug.LogError("Error! " + e),
        () => Debug.Log("Complete!")
    )
    ;
```

So this works pretty well, but it's kind of redundant because we could replace `cube.UpdateAsObservable()` with `Observable.EveryUpdate()` and get the exact same behavior. Might be nice if streams derived from a `GameObject` implicitly had their lifecycles limited, but I don't know if there's a good way to do that which fits all use cases.

**Comment by pelotom** [comment]
Ha! You commented right before me... so yeah, that solution works well enough :)
