### ISSUE TITLE
RepeatUntil sends OnCompleted

### ISSUE THREAD

**Issue by hsanno** [neuecc/UniRx#112]
Hello!

`RepeatUntilDestroy | RepeatUntilDisable` sends OnCompleted if it receives OnCompleted continuously (Similar to `RepeatSafe`).

`isRunNext` was added by this commit.
76978e9

This change was intended?

**Comment by neuecc** [comment]
Thank you.
Ah, no.
It's my mistake, I'll fix it!

**Comment by neuecc** [comment]
I've fixed.
It will be shipped in next release.

**Comment by hsanno** [comment]
Thank you for swift response :)
