### ISSUE TITLE
An error about coroutine at launch.

### ISSUE THREAD

**Issue by hotmiyacchi** [neuecc/UniRx#114]
いつもUniRXにはお世話になっています＆素晴らしいバージョンアップありがとうございます。
先日、UniRX5.0にバージョンアップした折から、起動時に

This asynchronous operation is already being yielded from another coroutine. An asynchronous operation can only be yielded once.

というエラーが出るようになり、本日も5.1を試させていただいたのですが、同様のエラーが出ました。

コールスタックは以下のようで、どうもSubscribeのネストをすると怪しいのかもと思ったものの、原因特定まではできず、
レポートを書かせていただきました。
（別のレポートにあるObservableWWW関連なのかもしれませんね）

今後のご参考になれば幸いです。

引き続き、どうぞよろしくお願いいたします。

UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UniRx.MainThreadDispatcher:StartCoroutine(IEnumerator) (at Assets/UniRx/Scripts/UnityEngineBridge/MainThreadDispatcher.cs:328)
UniRx.MainThreadDispatcher:SendStartCoroutine(IEnumerator) (at Assets/UniRx/Scripts/UnityEngineBridge/MainThreadDispatcher.cs:295)
UniRx.Operators.FromCoroutine`1:SubscribeCore(IObserver`1, IDisposable) (at Assets/UniRx/Scripts/UnityEngineBridge/Operators/FromCoroutine.cs:22)
UniRx.Operators.OperatorObservableBase`1:Subscribe(IObserver`1) (at Assets/UniRx/Scripts/Operators/OperatorObservableBase.cs:34)
UniRx.ObservableExtensions:Subscribe(IObservable`1, Action`1) (at Assets/UniRx/Scripts/Observer.cs:235)
ProfileBase:Initialize() (at Assets/UbikFramework/ProfileBase.cs:69)
ProfileBase:RandomProfile() (at Assets/UbikFramework/ProfileBase.cs:115)
MainScene:Awake() (at Assets/Scripts/MainScene.cs:72)
UnityEngine.Object:Instantiate(Object)
ApplicationState:get_Instance() (at Assets/UbikFramework/ApplicationState.cs:94)
SceneStateMachine:get_Root() (at Assets/UbikFramework/SceneStateMachine.cs:63)
StateMachine:get_IsRoot() (at Assets/UbikFramework/StateMachine.cs:73)
StateMachine:Awake() (at Assets/UbikFramework/StateMachine.cs:173)
SceneStateMachine:Awake() (at Assets/UbikFramework/SceneStateMachine.cs:152)
PKScene:Awake() (at Assets/Scripts/PKScene.cs:271)

ProfileBase:Initialize() (at Assets/UbikFramework/ProfileBase.cs:69)↓

			anonymousIconLoader.Subscribe (_ => { 				ObservableWWW.GetAndGetBytes (IconURL) 					.Retry(3) 					.Subscribe (x=>{ 						var tex = new Texture2D(32,32); 						tex.LoadImage (x); 						IconTex.Value = tex; 					} , 						ex =>{ 							Debug.Log( "Failed:" + IconURL ); 						}// onError			 					); 			} );

**Comment by neuecc** [comment]
Thank you for your report.

`This asynchronous operation is already being yielded from another coroutine. An asynchronous operation can only be yielded once.`
Hmn, what operation is calling twice?
Sorry, I can't grasp your stacktrace and code.

Is this error come from `anonymousIconLoader` or `ObservableWWW.GetAndGetBytes` ?
What is `anonymousIconLoader` ?

**Comment by neuecc** [comment]
This is minimal reproduce code.

```csharp
IEnumerator WaitTest(AsyncOperation c)
{
    yield return c;
}

void Start()
{
    var asyncOp = UnityEngine.SceneManagement.SceneManager.LoadSceneAsync("UnitAssertion");
    StartCoroutine_Auto(WaitTest(asyncOp));
    StartCoroutine_Auto(WaitTest(asyncOp));
}
```

I think this error come from your `LoadSceneAsync` codes.

**Comment by hotmiyacchi** [comment]
Thanks a lot for quick response and advice.

I’ll try to check again.

Many Thanks

**Comment by NoxMortem** [comment]
I wanted to add some more information as I've been running into the exact same mistake and this is the only hit on google. The reason lies within hot vs cold observers and side effects on Subscribe().
```
// Will yield the AsyncOperation twice:
var x = SceneManager.LoadSceneAsync(s.Name, LoadSceneMode.Additive).AsObservable();
x.Subscribe(_ =>{});
x.Subscribe(_ =>{});
// Will yield the AsyncOperation once:
var x = SceneManager.LoadSceneAsync(s.Name, LoadSceneMode.Additive).AsObservable().Share();
x.Subscribe(_ =>{});
x.Subscribe(_ =>{});
```

More information can be found here
*[Rx Sideeffects](http://www.introtorx.com/content/v1.0.10621.0/09_SideEffects.html#IssuesWithSideEffects)
*[Hot vs Cold Observables](https://medium.com/@benlesh/hot-vs-cold-observables-f8094ed53339)
*[RxJS.Share()](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/share.md
)
