### ISSUE TITLE
iOS Build And Run Error

### ISSUE THREAD

**Issue by st0326s** [neuecc/UniRx#116]
# Question
You following error message has trouble appears when you run with iOS build on Xcode?

It is the error that appears when you call the scene, but we are worried about what the good Once turned on the hand.

    ExecutionEngineException: Attempting to JIT compile method 'UniRx.InternalUtil.EmptyObserver`1<UniRx.Unit>:.cctor ()' while running with --aot-only.

    Rethrow as TypeInitializationException: An exception was thrown by the type initializer for UniRx.InternalUtil.EmptyObserver`1 at "C#fileName"..ctor () [0x00000] in <filename unknown>:0

# Example

There is the following definition in a class that was called from within the Unity of the Start method

        public Subject<Vector3> UIPositionChanged = new Subject<Vector3>();
        public IObservable<Unit> ObservableOnTiming;
        Subject<Unit> NotificationOnTiming = new Subject<Unit>();

# Development environment
Unity:5.3.0f4
UniRx:4.8.2
Xcode:6.4
iPhone iOS version:8.4

**Comment by neuecc** [comment]
Hmn, its issue maybe occurs on UniRx 5.0 and scripting backend is mono.

4.8.2
https://github.com/neuecc/UniRx/blob/4.8.2/Assets/UniRx/Scripts/InternalUtil/ListObserver.cs

After 5.0
https://github.com/neuecc/UniRx/blob/master/Assets/UniRx/Scripts/InternalUtil/ListObserver.cs#L67

Is your scripting backend is mono or IL2CPP?
Please change IL2CPP and use UniRx 5.*.

**Comment by st0326s** [comment]
Thank you very much.

There is still a problem, but I worked by Unirx5.1.0.

There is one thing to be worried about.
Even while it was no problem running now until the "Mono"
"IL2CPP" In Why was it that no longer work and if not?

And say why,
"IL2CPP" is is still thought not to be a stable operation
It is because I want to be able to run it in the stable is "Mono".

**Comment by neuecc** [comment]
Now, iOS market only accept 64bit support.
Unity's iOS 64bit support only provides IL2CPP.
So, I recognize IL2CPP is stable on iOS.

AOT support need some hacks and it cause performance issue(for example, I can't use generic singleton(`EmptyObserver<T>.Instance`, can't use struct `Unit`, etc...)

**Comment by st0326s** [comment]
Certainly it is as you say you.
You do not need to build in the "Mono" in a future release

Thank you for your reply.
