### ISSUE TITLE
ExecutionEngineException: Attempting to JIT compile method 

### ISSUE THREAD

**Issue by Lailore** [neuecc/UniRx#117]
Hello, I build my game for IOS and get this exeption:
ExecutionEngineException: Attempting to JIT compile method 'UniRx.InternalUtil.EmptyObserver`1<int>:.cctor ()' while running with --aot-only.

I just create new subject<int>

How I can fix this?

**Comment by neuecc** [comment]
Please change ScriptBackend to `IL2CPP` on iOS Settings.

**Comment by Lailore** [comment]
I can't do this, because i use dependency injection and il2cpp remove constructors :(

**Comment by neuecc** [comment]
Would you try to `PreserveAttribute` ? 
http://docs.unity3d.com/ScriptReference/Scripting.PreserveAttribute.html

**Comment by Lailore** [comment]
I start use il2cpp and link.xml.
Thanks for help.
