### ISSUE TITLE
Support for Unity's code hot swapping

### ISSUE THREAD

**Issue by doppioslash** [neuecc/UniRx#150]
Unity has a mostly ignored ability to load changed code while a game is playing.
See [this gist](https://gist.github.com/cobbpg/a74c8a5359554eb3daa5) for the best write-up I could find on it.
I wanted to use UniRx, but I see that changing anything in the example code while playing the game results in multiple errors.

How hard do you think it would be to add it? 
I'm willing to do it myself, but I need to know how hard it would be.

**Comment by neuecc** [comment]
Thanks, great document.
But so... yes, it is very hard. I think it is impossible.
Observable operators has many inner states which does not serializable.
Some operators uses coroutine heavily.

**Comment by doppioslash** [comment]
Thanks, I'll give up on it.
