### ISSUE TITLE
[Slides] [Examples] Simple game dev related sample for UniRx

### ISSUE THREAD

**Issue by Xerios** [neuecc/UniRx#151]
I recently did a small talk on UniRx during Brussels Game Dev meetup Brotaru.

It shows off small extremely simple example ( with animated gifs and all ) for using UniRx.

http://slides.com/sammegidov/unirx#/
Examples source : https://github.com/xerios/unirxSimple

Thanks for such an amazing library neuecc !

**Comment by neuecc** [comment]
Thank you very much!
I am very happy.

**Comment by neuecc** [comment]
I've added your slide to ReadMe(Is it okay?).
https://github.com/neuecc/UniRx#reference

Thanks.

**Comment by Xerios** [comment]
Of course it is, it's one of the reasons why I posted it here :)

I'm gonna do another one on CompositeDisposable using a simple game example later on.
Mostly because I had hard time finding any proper Rx structure setup for games, so I had to come up with my own.

**Comment by Xerios** [comment]
https://github.com/Xerios/UniRxSimpleGame

Added this one because of lack of simple game examples

**Comment by neuecc** [comment]
Great!
I've added!

**Comment by RDeluxe** [comment]
Sorry, I have the impression I'm doing some room cleaning, but may I suggest to close this issue ?
@neuecc the repo would look better with less opened issues :)

**Comment by Xerios** [comment]
Yes. BAM! Closed.
