### ISSUE TITLE
UniRx doesn't account for threads w/r to CurrentThreadScheduler; so ObserveOn and SubscribeOn mean nothing

### ISSUE THREAD

**Issue by bfloydgsn** [neuecc/UniRx#157]
compare CurrentThreadScheduler to vanilla version. 
https://github.com/neuecc/UniRx/blob/373ed71078f7f31826299bc488d9cd7ed5dd68c8/Assets/Plugins/UniRx/Scripts/Schedulers/CurrentThreadScheduler.cs

https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Core/Reactive/Concurrency/CurrentThreadScheduler.cs

**Comment by neuecc** [comment]
Thank you for reporting.
But sorry, where is it?
I think `[ThreadStatic]` works with multi threading, where am I missing?

**Comment by bfloydgsn** [comment]
You can see all the references to Thread.CurrentThread.ManagedThreadId to map the queues

**Comment by bfloydgsn** [comment]
`
[Test]
		public void ObserveOnTest() {

			var threadId = Thread.CurrentThread.ManagedThreadId;

			Observable.Start<string>(
				delegate {
					return "test";
				}
			).ObserveOn(Scheduler.CurrentThread).Subscribe(
				(result) => {
					Assert.AreEqual(threadId, Thread.CurrentThread.ManagedThreadId);
				}
			);
		}
`
though technically this will pass because nunit sucks w/r to threading. but put a breakpoint and check

**Comment by neuecc** [comment]
Managing Dictionary is `NO_TLS` pass, it is not used normally. 

But I find breaking compatibility with RxNet and UniRx in `Observable.Start`.
RxNet's Observable.Start run immediate(hot observable) but UnIRx's Start run deffered(cold observable).

**Comment by neuecc** [comment]
Can I close this issue?

**Comment by bfloydgsn** [comment]
I see your point. However, the current UniRx (!NO_TLX) implementation does not work for the example I provided. The expected result is that the callback will be on the same thread, which it will not be in UniRx. It appears to me that NO_TLS is the only way to ensure the callback is scheduled on the correct thread. I'm implementing to test tonight, but accept I could be wrong.

I'm happy to open a separate issue for the broken example if that is better, in which case feel free to close.

**Comment by neuecc** [comment]
`Scheduler.CurrentThread` does not means return to declared thread.
`CurrentThread` means running same thread on execution thread(it is similar to Immediate).

```csharp
// threadId:1
var threadId = Thread.CurrentThread.ManagedThreadId;
UnityEngine.Debug.Log("Outer:" + threadId);

Observable.Start<string>(
    delegate {
        // run on threadpool, threadId:2
        UnityEngine.Debug.Log("Start:" +Thread.CurrentThread.ManagedThreadId);
        return "test";
                    }
    )
    .ObserveOn(Scheduler.CurrentThread)
    .Subscribe(
        (result) => {
            // run on threadpool(same on Start) threadId:2
            UnityEngine.Debug.Log("Subscribe:" + Thread.CurrentThread.ManagedThreadId);
        }
    );
```

**Comment by bfloydgsn** [comment]
http://www.introtorx.com/content/v1.0.10621.0/15_SchedulingAndThreading.html

Scheduler.Immediate will ensure the action is not scheduled, but rather executed immediately.

Scheduler.CurrentThread ensures that the actions are performed on the thread that made the original call. This is different from Immediate, as CurrentThread will queue the action to be performed. We will compare these two schedulers using a code example soon.

Scheduler.NewThread will schedule work to be done on a new thread.

Scheduler.ThreadPool will schedule all actions to take place on the Thread Pool.

Scheduler.TaskPool will schedule actions onto the TaskPool. This is not available in Silverlight 4 or .NET 3.5 builds.

**Comment by neuecc** [comment]
Yes, `performed on the thread that made the original call` 's `original call` means where OnNext in pipeline called.
If in the ThreadPool, current thread is ThreadPool.

You can test with ConsoleApp on Rx.NET, it is same as UniRx.

```csharp
// Rx.NET

Console.WriteLine("Outer:" + Thread.CurrentThread.ManagedThreadId); // 1

// simulate deferrred Observable.Start
Observable.Create<Unit>(observer =>
{
    ThreadPool.QueueUserWorkItem(_ =>
    {
        Console.WriteLine("Start:" + Thread.CurrentThread.ManagedThreadId); // 4
        observer.OnNext(Unit.Default);
        observer.OnCompleted();
    });
    return System.Reactive.Disposables.Disposable.Empty;
})
.ObserveOn(CurrentThreadScheduler.Instance)
.Subscribe(x =>
{
    Console.WriteLine("Subscribe:" + Thread.CurrentThread.ManagedThreadId); // 4
});

Console.ReadLine();
```

**Comment by bfloydgsn** [comment]
Thanks for the feedback
