### ISSUE TITLE
AOT/JIT problem on iOS for IObservable<bool?>

### ISSUE THREAD

**Issue by Pizoline** [neuecc/UniRx#158]
Dear,

In my code, I use something like:
`
IObservable<bool?> observable = ...;
observable.Subscribe(MyFunc);
`
but the subscription cause AOT problem on iOS for `Stubs<Nullable<bool>>`

I tried avoiding the use of Strubs by writing:
`
observable.Subscribe(b => MyFunc(b), e => Debug.LogError(e), () => {});
`
but same problem occurs

I think it come from Observer.cs line 11:
`
            if (onNext == Stubs<T>.Ignore) // need compare for avoid iOS AOT
`

I tried using another syntax:
`
observable.Do(MyFunc).Subscribe();
`
but I have another AOT problem for `UniRx.InternalUtil.ThrowObserver<Nullable<Bool>>.Instance`

Finally, it works if I provide my own observer:
`
observable.Do(MyFunc).Subscribe(UniRx.InternalUtil.ThrowObserver<Nullable<Bool>>.Instance);
`

Subsidiary question:
There is a special care of AOT problem for `Stubs<T>`, lines 11, 53 and 498
but there isn't this kind of protection for `Stubs<T1, T2>` and `Stubs<T1, T2, T3>`

**Comment by neuecc** [comment]
Thank you for reporting.
Do you use AOT option on iOS?
UniRx 5.* drops AOT support, you can only use IL2CPP for iOS.
