### ISSUE TITLE
Subject<T> is automatically stopped when scene is changed.

### ISSUE THREAD

**Issue by kkc0923** [neuecc/UniRx#171]
I used UniRx for singleton manager class. It has manu Subject<T> for broadcasting events. It works find at single scene, but when I changed scene (singleton class is still alive because it is marked by DontDestroyOnLoad), all of Subject<T> ignores my events.

**Comment by kkc0923** [comment]
UniRx 5.3.0 with Unity 5.3.5p5.

**Comment by neuecc** [comment]
`Subject<T>` stops when disposed.
If register subject to any scene, disposed and stopped.
I think it is trigger, is please check? or please submit minimal repro code.

**Comment by kkc0923** [comment]
Hmm, I tested minimal code with latest UniRx and Unity 5.4.1p1, this can't be reproduced. In this time, I closed this issue. Thanks.
