### ISSUE TITLE
Question about replacing delegate messaging

### ISSUE THREAD

**Issue by pmtolk** [neuecc/UniRx#182]
I am trying to learn and understand UniRx and as a first step would like to replace my messaging system with UniRx. However, I do not fully understand how to create a caller and listener for a function. Thus far I was able to get the listener and caller to work for types but not for method types. In the old Unit Messaging system, http://wiki.unity3d.com/index.php/Advanced_CSharp_Messenger the filtering is done on a string lookup table and that is what I would like to replace first with UniRx.

```
using UnityEngine;
using System.Collections;
using UniRx;

public class Caller : MonoBehaviour {
	void Start () {
		MessageBroker.Default.Publish("HelloWorld");//this is working as a type 
		MessageBroker.Default.Publish(this);//this is working as a type
               //how can I send a message to all listeners this does not work
		MessageBroker.Default.Publish(OnPause);//this does not work
               //this is the old messenger system
              Messenger<float>.Broadcast("FunctionTest", 1.0f, MessengerMode.DONT_REQUIRE_LISTENER);
	}

}

public class Listener : MonoBehaviour {
	void Awake () {
		MessageBroker.Default.Receive<string>().Subscribe(OnLogIt);//this is working 
		MessageBroker.Default.Receive<Caller>().Subscribe(GotCall);//this is working
               //how can I receive an event ent and receive it???
		MessageBroker.Default.Receive<OnPause>().Subscribe(OnPauseGotIt);
               //this is the old messenger system
               Messenger<float>.AddListener("FunctionTest", TestCallbackFloat);
	}
	void OnLogIt(string x){
		UnityEngine.Debug.Log(x);
	}
	void GotCall(Caller c){
		UnityEngine.Debug.Log("got call "+c.name);
	}
	void OnPauseGotIt(OnPause o){
               Debug.Log("OnPauseGotIt() was called."+o.name);
	}
        void TestCallbackFloat(float f) {
		Debug.Log("TestCallback() was called."+f);
	}
}
```

**Comment by neuecc** [comment]
`MessageBroker` is filter by instance type.
`MessageBroker.Default.Publish(OnPause);//this does not work`
This lines `OnPause` is property? type definition?
If it is type definition, does not work, maybe you can change
`MessageBroker.Default.Publish(new OnPause { name = "..." });`

**Comment by pmtolk** [comment]
How can I publish a message that is specified by a string match?
This is the old way of sending messages that I want to replace and it calls the functions that have the same string. How would you suggest doing this with UniRx?

Messenger.AddListener("OnStartGame", StartGame);
Messenger.Broadcast("OnStartGame");
Messenger.AddListener("OnGameOver", EndGame);
Messenger.Broadcast("OnGameOver");

void StarGame(){}
void EndGame(){}

**Comment by neuecc** [comment]
You can send Enum?

```
public enum GameState
{
    StartGame, GameOver
}

MessageBroker.Default.Publish(GameState.StartGame);
MessageBroker.Default.Publish(GameState.GameOver);

---

MessageBroker.Default.Receive<GameState.StartGame>().Where(x => x == GameState.StartGame).Subscribe();
```

**Comment by pmtolk** [comment]
Yes, that is perfect!

In a Unity fsm such as https://github.com/thefuntastic/Unity3d-Finite-State-Machine
the states have callbacks 

    Enter
    Exit
    FixedUpdate
    Update
    LateUpdate
    Finally

Is it possible to add these callbacks with UniRx?
