### ISSUE TITLE
Simple delay

### ISSUE THREAD

**Issue by duchanhleo** [neuecc/UniRx#187]
hello, I'm new for RX
I need to do something after some seconds. Example
`class Delay_Simple
{
    static void Main()
    {
        var oneNumberEveryFiveSeconds = Observable.Interval(TimeSpan.FromSeconds(5));

        // Instant echo
        oneNumberEveryFiveSeconds.Subscribe(num =>
        {
            Console.WriteLine(num);
        });

        // One second delay
        oneNumberEveryFiveSeconds.Delay(TimeSpan.FromSeconds(1)).Subscribe(num =>
        {
            Console.WriteLine("...{0}...", num);
        });

        // Two second delay
        oneNumberEveryFiveSeconds.Delay(TimeSpan.FromSeconds(2)).Subscribe(num =>
        {
            Console.WriteLine("......{0}......", num);
        });

        Console.ReadKey();
    }
}
But UniRX have not that method for delay. Please guide me if we can do it.
Thank you`

**Comment by duchanhleo** [comment]
I tried another way. But the Subscribe has been called twice. After 6 seconds and after 4 seconds although I set 10 seconds for param
`Observable.Timer(TimeSpan.FromSeconds(GameConfig.TURN_DURATION)).Subscribe(time =>
        {
            CLog.Log(this, "End count down " + time);
            //var next = ((int)CurrentTurn) + 1;
            //if (next > GameConfig.PLAYER_NUMBER)
            //    next = 1;
            //CurrentTurn = (GameSlot)next;
        });`

**Comment by hiramtan** [comment]
`            Observable.Timer(TimeSpan.FromSeconds(5)).Subscribe(_ =>
            {
              Debug.Log("delay 5s");
            }).AddTo(this);`
