### ISSUE TITLE
ReactiveCollection.Dispose() not disposing countChanged subject.

### ISSUE THREAD

**Issue by RobGraat** [neuecc/UniRx#193]
The Dispose method of ReactiveCollection seems not to be disposing the ReactiveCollection.countChanged subject:

    public void Dispose()
    {
        if (isDisposed) return;
        isDisposed = true;
    
        DisposeSubject(ref collectionReset);
        DisposeSubject(ref collectionAdd);
        DisposeSubject(ref collectionMove);
        DisposeSubject(ref collectionRemove);
        DisposeSubject(ref collectionReplace);
    }

Add:

         DisposeSubject(ref countChanged);

**Comment by neuecc** [comment]
Oh..., yes!!!
thanks for report!
