### ISSUE TITLE
ObjectPool.Dispose() not virtual

### ISSUE THREAD

**Issue by gregee123** [neuecc/UniRx#197]
Hello.

Could you mark ObjectPool<T>.Dispose() and AsyncObjectPool<T>.Dispose() as virtual so that derived classes can do their own housekeeping?

**Comment by neuecc** [comment]
`protected virtual void Dispose(bool disposing)` is virtual(Dispose calls `Dispose(true)`, in internal).
Is it ok?

**Comment by gregee123** [comment]
Yes.

public virtual Dispose()  

would be ok.

For now I have to hide the Dispose() from the base class using 'new' keyword I'd rather to be able to use 'override' keyword in my derived class, if that's ok.

**Comment by neuecc** [comment]
No, you should only implements Dispose(bool) method.
This is standard pattern of implements Dispose Method.
https://msdn.microsoft.com/en-us/library/fs2xkftw(v=vs.110).aspx

**Comment by gregee123** [comment]
That's how I'll do it then.
