### ISSUE TITLE
Implements to 4/19

### ISSUE THREAD

**Issue by neuecc** [neuecc/UniRx#2]
Memo - Methods
## Scheduler

EventLoop
NewThread
VirtualTimeScheduler
HistoricalScheduler
## Disposable

RefCountDisposable
ScheduledDisposable
## Subject

BehaviorSubject
ReplaySubject
## LINQ-Generation

Empty
Never
If
Generate
FromAsync
FromAsyncPattern
FromEvent
FromEventPattern
For
Case
Interval
Range
Repeat
Return
Start
Throw
Timer
Using
While
## LINQ

Aggregate
All
Amb
And/Then/When
Any
AsObservable
Average
Buffer
Cast
Catch
Chunkify
Collect
CombineLatest
Concat
Contains
Count
Create
DefaultIfEmpty
Defer
Delay
DelaySubscription
Dematerialize
Distinct
DistinctUntilChanged
Do
DoWhile
ElementAt
ElementAtOrDefault
First
FirstOrDefault
ForEach
GroupBy
GetEnumerator
GroupByUntil
GroupJoin
IgnoreElements
IsEmpty
Join
Last
LastOrDefault
Latest
LongCount
Materialize
Max
MaxBy
Merge
Min
MinBy
MostRecent
Multicast
Next
ObserveOn
OfType
OnErrorResumeNext
Publish
PublishLast
RefCount
Replay
Retry
Sample
Scan
Select
SelectMany
SequenceEqual
Single
SingleOrDefault
Skip
SkipLast
SkipUntil
SkipWhile
StartWith
Subscribe
SubscribeOn
Sum
Switch
Synchronize
Take
TakeLast
TakeLastBuffer
TakeUntil
TakeWhile
Throttle
TimeInterval
Timeout
Timestamp
ToArray
ToAsync
ToDictionary
ToEvent
ToEventPattern
ToList
ToLookup
ToObservable
Wait
Where
Window
Zip
## LINQ.ErrorHandling

Finally

**Comment by wavebit** [comment]
I find that IObservable<T>.GetEnumerator is not supported.

**Comment by RDeluxe** [comment]
FromAsync does not seem to be supported either

**Comment by vml933** [comment]
Is Unirx support ElementAt and Count in the future?
