### ISSUE TITLE
IObservable Windows Store 10 builds

### ISSUE THREAD

**Issue by HaakonL** [neuecc/UniRx#200]
Getting issues with IObservable (possibly also other) when trying to build for Windows Store Universal 10 in Unity 5.5.0.

The type or namespace name 'IObservable<>' could not be found (are you missing a using directive or an assembly reference?)

**Comment by neuecc** [comment]
Is this https://github.com/neuecc/UniRx#windows-storephone-app-netfx_core issue?

```csharp
using System;
using UniRx;
```

and define

```csharp
IObservable<T> ...
```

**Comment by HaakonL** [comment]
Hi,

no, unfortunately not. The error comes right away when trying to build for
Windows Store Universal 10. Just by attaching this simple class to a
gameobject is enough:

using UnityEngine;
using UniRx;

public class SomeController : MonoBehaviour
{
    public IObservable<bool> SomeProperty { get; set; }
}



--

Best regards,
*Haakon Langaas Lageng*

*Monkeybin AS*
Phøne: +47 997 90 091

http://monkeybin.com <http://www.monkeybin.com>

2016-12-20 5:31 GMT+01:00 Yoshifumi Kawai <notifications@github.com>:

**Comment by neuecc** [comment]
`using System;` is required.

```
// In Editor, used UniRx.IObservable<T> but build time, used System.IObservable<T>
using System;

using UnityEngine;
using UniRx;

public class SomeController : MonoBehaviour
{
    public IObservable<bool> SomeProperty { get; set; }
}
```

**Comment by HaakonL** [comment]
Hi,

thanks for pointing this out. It resolved the issue and our Windows Store builds are working again.

:+1:

**Comment by neuecc** [comment]
good!

**Comment by mhle** [comment]
@neuecc I still see this issue using Unity 5.6.1f1 and UniRx 5.5.0. Building for Windows Store Universal 10, UWP SDK v10.0.15063.0

Getting:

` error CS0246: The type or namespace name `IObservable' could not be found. Are you missing an assembly reference?`

Code:
```
using System.Collections.Generic;
using System;
using UniRx;
using System.Linq;

public class MyClass {
    public IObservable<GraphEdgePresenter> EdgePresentersAdded { get; private set; }
    public IObservable<GraphEdgePresenter> EdgePresentersRemoved { get; private set; }
}
```

**Comment by mhle** [comment]
Similar issue when using CompositeDisposable. Getting:

`error CS0012: The type `System.Collections.Generic.ICollection`1<System.IDisposable>' is defined in an assembly that is not referenced. Consider adding a reference to assembly`

Code: 
```
CompositeDisposable disposables = new CompositeDisposable();
```
Seems to conflict with System.Reactive.Disposables.CompositeDisposable.
