### ISSUE TITLE
combine FromEvent and ToYieldInstruction doen't work what i expected.

### ISSUE THREAD

**Issue by netpyoung** [neuecc/UniRx#202]
I think it will be worked. but doesn't called after ToYieldInstruction;

~~~cs
var xx = Observable.FromEvent (h => window.OnHideCalled += h, h => window.OnHideCalled -= h);
yield return xx.ToYieldInstruction();

Debug.Log ("Done");
yield return null;
~~~

follow code is worked.

~~~cs

var xx = Observable.FromEvent (h => window.OnHideCalled += h, h => window.OnHideCalled -= h);
SingleAssignmentDisposable a = new SingleAssignmentDisposable ();
a.Disposable = xx
		.Subscribe((_) => {
			Debug.Log ("Doneeee");
			a.Dispose();	
		});

while (!a.IsDisposed) { yield return null; }

Debug.Log ("Done");
yield return null;
~~~

**Comment by sbergen** [comment]
(I know I'm answering to a very old issue, but...)

When you `yield return` an observable, it will wait for completion, not for a single value. `FromEvent` being a hot observable, it will keep going forever, unless you terminate it.

E.g. just doing `Observable.FromEvent(...).Take(1)` would work as you expected with the yield.

**Comment by netpyoung** [comment]
@sbergen thanks for reply. I saw your answer but i forget this issue to close.
