### ISSUE TITLE
Is EveryFixedUpdate called in same frame or next frame?

### ISSUE THREAD

**Issue by aelr** [neuecc/UniRx#209]
I couldn't find this in the docs, either.  Thanks for any insight.

**Comment by neuecc** [comment]
Where do you start subscrption?
In update? In coroutine-update? In fixed-update? In last-update?
But FixedUpdate's lifecycle is different with standard update.
It is undefined.

**Comment by aelr** [comment]
Sometimes I start it via a subscription to `Observable.EveryFixedUpdate`, other times from a subscription to `Observable.EveryUpdate`.  Is its behavior deterministic for each of those two cases?  If so, what is the expected behavior?

**Comment by neuecc** [comment]
EveryUpdate/EveryFixedUpdate follows `WaitForFixedUpdate`
https://docs.unity3d.com/Manual/ExecutionOrder.html
The frequency of FixedUpdate differs according to the setting, and it follows the setting of Unity.

**Comment by aelr** [comment]
Thanks!  That is exactly what I needed to know.
