### ISSUE TITLE
ReactiveCollection.cs subscription to disposed collection

### ISSUE THREAD

**Issue by JohnPoison** [neuecc/UniRx#215]
Hi I've stumbled on ReactiveCollection implementation and found that flag isDisposed is never being set. I guess it is a potential bug, since this flag is checked during ObserveAdd and other methods.

https://github.com/neuecc/UniRx/blob/0f4659c201062e1da37e86f3cb23aeddcedd1e6c/Assets/Plugins/UniRx/Scripts/UnityEngineBridge/ReactiveCollection.cs#L149

**Comment by JohnPoison** [comment]
Duplicate #193

**Comment by hendrik-schulte** [comment]
This is actually not a duplicate of #193 and has not been fixed yet. 
`isDisposed` should probably be renamed to `disposedValue` which is actually being set to true when `Dispose()` is called.
