### ISSUE TITLE
Need help AOT issues

### ISSUE THREAD

**Issue by neonaleon** [neuecc/UniRx#216]
Hello, 

I tried putting my game on PS4, and have the following issue:
ExecutionEngineException: Attempting to JIT compile method 'UniRx.UnityEqualityComparer/RuntimeTypeHandlerCache`1<bool>:.cctor ()' while running with --aot-only.

I know PS4 is not officially supported, but I am trying. Is there any possible workaround for this issue?

**Comment by neuecc** [comment]
UniRx only supports IL2CPP.
Could you try to use IL2CPP?

**Comment by neonaleon** [comment]
I tried IL2CPP and got it working!
Thanks a lot!!
