### ISSUE TITLE
An error is occured when using `DelayFrame()` operator but not doing anything.

### ISSUE THREAD

**Issue by monry** [neuecc/UniRx#225]
# Summary

Play a Scene with only the GameObject attached with the following code and exit without doing anything, an error will occur at the end.

# Sample code

```csharp:sample.cs
using UnityEngine;
using UniRx;

class Sample : MonoBehaviour {
    public void Start() {
        Subject<Unit> empty = new Subject<Unit>();
        empty.DelayFrame(1).Subscribe(_ => {});
    }
}
```

# Error message

`Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects from OnDestroy?)`

# Note

It may be possible to generate MainThreadDispatcher within OnCompleted of DelayFrame.

Running `empty.OnCompleted();` at the end of the above code will not occur an error.

**Comment by JimW** [comment]
How about if you put:

 .AddTo(this) 

to the end of your subscription?

**Comment by monry** [comment]
Problem solved!
Thank you!!
I completely forgot the existence of it...
