### ISSUE TITLE
Allow untrusted SSL for ObservableWWW

### ISSUE THREAD

**Issue by nlhkh** [neuecc/UniRx#231]
I have an online service with self-signed SSL certificate, and is thus deemed untrusted. `ObservableWWW` is giving error because of this. Is there any way I can ignore this untrusted SSL and proceed with the request?

**Comment by Arodus** [comment]
You can do that easily on your own by using:

    ServicePointManager
        .ServerCertificateValidationCallback +=  (sender, cert, chain, sslPolicyErrors) => true;

You maybe should add a own validation function instead of just trusting every certificate.

**Comment by nlhkh** [comment]
`ServicePointManager` does not exist in UWP or Unity. I tried using the package `Windows.Net` instead but still with no luck.

**Comment by Arodus** [comment]
ServicePointManager is part of the System.Net namespace and is already contained in .Net 3.5 (https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager(v=vs.90).aspx)
There is also a [Thread in the Unity community forum](https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager(v=vs.90).aspx) on how to trust self signed certificates.

**Comment by nlhkh** [comment]
Found it! Thanks @Arodus
