### ISSUE TITLE
Unity 2017.2: deprecated CallbackFunction EditorApplication.playmodeStateChanged used in ScenePlaybackDetector.cs

### ISSUE THREAD

**Issue by cloudcover** [neuecc/UniRx#253]
https://github.com/neuecc/UniRx/blob/0f4659c201062e1da37e86f3cb23aeddcedd1e6c/Assets/Plugins/UniRx/Scripts/UnityEngineBridge/ScenePlaybackDetector.cs#L55

Per compilation warning messages,` CallbackFunction EditorApplication.playmodeStateChanged` has been replaced with `static event Action<PlayModeStateChange> playModeStateChanged`, which has a lambda expression syntax that needs to reference the newly-named instance of `enum PlayModeStateChange` instead of taking no arguments.

I didn't do anything with the instance, so line 55 of _ScenePlaybackDetector.cs_ now becomes
`EditorApplication.playModeStateChanged += (PlayModeStateChange _pmsc) =>`

**Comment by altschuler** [comment]
It's fixed in https://github.com/neuecc/UniRx/commit/bfb300ea967a4260ef6afcb27a0d33edbdadeb2c
