### ISSUE TITLE
How to use SubscribeOnMainThread? It seems never working

### ISSUE THREAD

**Issue by zhenghongzhi** [neuecc/UniRx#282]
Simple code for test. `ObserveOnMainThread` works perfectly. Is there something I misunderstand with 
`SubscribeOnMainThread`?
```
Observable.Start(() => Unit.Default) // asynchronous work
    .SubscribeOnMainThread()
    .Subscribe(_ =>
    {
        GameObject.CreatePrimitive(PrimitiveType.Cube);
    });
```

I read the code and find that `SubscribeOnObservable` line:24. observer is subscribed to source and source never knows the scheduler.
```
m.Disposable = scheduler.Schedule(() =>
            {
                d.Disposable = new ScheduledDisposable(scheduler, source.Subscribe(observer));
            });
```

**Comment by tomerpeled** [comment]
Well, it seems like the issues that I encountered with, happened due to Unity's bug:

(827984) - Scripting: Fixed deadlocks and pauses when using System.Threading.Monitor.

After promoting my Unity version to 2017.3.03p the deadlock and pauses vanished :)

**Comment by dogramacigokhan** [comment]
`SubscribeOnMainThread` means that you are subscribing (therefore **starting** the task [for cold observables]) in main thread whereas `ObserveOnMainThread` means that you are **observing** (listening) `onNext` messages in main thread.

When you are using `Observable.Start` method, the task will be run on the ThreadPool by default. So use it with the `ObserveOnMainThread` to access Unity API in the `Subscribe` method.

**Comment by zhenghongzhi** [comment]
Hi @dogramacigokhan ,
Thank you very much!
