### ISSUE TITLE
.net standard 2.0 support?

### ISSUE THREAD

**Issue by grofit** [neuecc/UniRx#289]
Unity 2018.1 adds support for .net standard 2.0 but if you enable it UniRx seems to throw various errors around namespace ambiguities, its easy enough to reproduce, just add unirx to the project and enable .net 4 experimental and .net standard 2.0 instead of .net subset.

**Comment by TheTrigger** [comment]
I get these errors with .net standard 2.0;
- `The best overloaded method match for UniRx.Observable.WhenAll<object>(params UniRx.IObservable<object>[]) has some invalid arguments`
- `Argument #1 cannot convert UniRx.IObservable<UnityEngine.AssetBundle> expression to type UniRx.IObservable<object>`

Code:
`var query = Observable.WhenAll<object>(ObservableWWW.LoadFromCacheOrDownload(....), ObservableWWW.Get(....));`

Will be fixed? or there are a fast workaround?

**Comment by grofit** [comment]
@neuecc any chance you could chime in or elect someone else to also assist in maintaining the lib?

**Comment by neuecc** [comment]
solved in 6.0.0
