### ISSUE TITLE
IProgress defined multiple times in Unity 2017 using C# 4.6 compiler?

### ISSUE THREAD

**Issue by meds** [neuecc/UniRx#293]
I noticed this error after importing UniRx to my Unity project after setting the compile version to 4.6. I suspect the issue is in IProgress where the line is:

`#if !(NETFX_CORE || NET_4_6)`

I have no idea what's going on since it makes sense that if NET_4_6 is defined as it shouold be with that compiler version then that if block should return false and not compile.

Curiously if I comment out the preprocessor lines I no longer get the error which makes less than no sense since now nothing is guarding against that.

Not sure  this might be a Unity compiler bug or I'm doing something wrong.

**Comment by neuecc** [comment]
in 6.0.0, definition is using `#if !(NETFX_CORE || NET_4_6 || NET_STANDARD_2_0 || UNITY_WSA_10_0)` , maybe soleved.
