### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by willispinaud** [neuecc/UniRx#319]

**Comment by Anduil** [comment]
I have same question

**Comment by neuecc** [comment]
Today(Yesterday) I submitted and approved new version to UnityAssetStore.
https://github.com/neuecc/UniRx/pull/318

I'm writing release note and readme now.

**Comment by neuecc** [comment]
I've added release note and updated ReadMe.
And I've post the blog, detail of UniRx.Async and deteminiation of keep development of UniRx.
https://medium.com/@neuecc/zero-overhead-async-await-for-unity-by-custom-async-statemachine-with-c-7-0-6808695733ba
