### ISSUE TITLE
API: UniTask.Delay is inconsistent with .NET Task.Delay

### ISSUE THREAD

**Issue by idbrii** [neuecc/UniRx#320]
I read your announcement blog post and UniRx.Async looks pretty cool. However, the inputs to Delay seem confusing:

    public static UniTask<int> Delay(int delayFrameCount, PlayerLoopTiming delayTiming = PlayerLoopTiming.Update, CancellationToken cancellationToken = default(CancellationToken))
	public static UniTask Delay(TimeSpan delayTimeSpan, PlayerLoopTiming delayTiming = PlayerLoopTiming.Update, CancellationToken cancellationToken = default(CancellationToken))

They're the same except for the first argument, which makes sense except that it's easy to confuse them. Also, .NET's [Task.Delay](https://msdn.microsoft.com/en-us/library/hh194873(v=vs.110).aspx) takes milliseconds or a TimeSpan (both are effectively the same thing), so this is doubly confusing.

I'd suggest to rename the framecount variant to avoid user confusion.

Suggestions: Defer, Wait, Skip, FrameDelay.

**Comment by neuecc** [comment]
Thanks, yes i agree.
UniRx exists `DelayFrame` method.
I'll change `DelayFrame` to next update.

**Comment by neuecc** [comment]
6.1.0(6.1.2) includes this changes.
