### ISSUE TITLE
Compilation or DLL load : Unable to use UniRx feature 

### ISSUE THREAD

**Issue by Shadsa** [neuecc/UniRx#323]
Hi @neuecc 

First, thank you for this awesome tools. It does exactly what I aim for.

However, I have hard time to figure out what's going on with my setup. I'm working on an AR project on Hololens, and I'm using Unity for UI design. I've see on [this thread](https://forums.hololens.com/discussion/894/mmvm-mvc-for-hololens-development) that this should work on HoloLens device.
I'm working with Unity 2017.4 and VS community 2017, with Unity toolchain setup on.

Each time I tryed to compile either any UniRx project or try to use a raw dll in my project, it end up with a build error. The odd thing is that the error is not in code itself, but directly related to the assembly : project and subproject, either imported in an existed one (and functional one) or raw-compiled can't found any Unity dll. Even if thos dll are used in the same project and register in the assembly. I also tryed the nuget version, and got a version-non-supported error (I gess the nuget is a bit out of date ?)

I really don't see what I'm doing wrong (because I think the matter is on my side for sure).

For more context, I had to find a workaround due to some heavy freeze in remote API call (loading texture from URL). The best way is async call but, so far, I can't manage to make them work side by side with yield and coroutine from Unity.

Thanks for any help/idea/response !
Kind regards, 
Shad

**Comment by neuecc** [comment]
Yes, NuGet DLL is not for UWP.
You can download from releases page(.unitypackage) or download from AssetStore.
Could you show(error message/screenshot) your error?

**Comment by Shadsa** [comment]
Thanks for your answer @neuecc . I already try to use it by downloading it directly from the Unity assets store, but when I build the project under Unity and then open it in VS for the code-work part before testing it on HoloLens, no scripts or library related to UniRx could be found in it. 
I'm trying to reproduce the exact same error, and I'll send you an update. If I remember correctly, it's directly related to Visual Studio compiler : when trying to assemble all part, the subpart containing the UniRx DLL or code couldn't find UnityEngine. (and so go on for every Unity module).

**Comment by Shadsa** [comment]
Okay, so I'm unable to redo it so I'll assume that it was just a compilation matter and so it directly depend of my project setup. 
I have give a try to the DLL redone by[ this repo ](https://github.com/selfsx/UniRx). So far the DLL compile, and don't display any error when I'm building the solution, but it seems that it jsut don't work when I try to use those feature. For exemple, even the given setup code on the repo page doesn't work : 
```
[InitializeOnLoad]
  public class UniRxInitializer {
    static UniRxInitializer() {
      ScenePlaybackDetector.InitializeOnLoad();
    }

    [DidReloadScripts]
    public static void DidReloadScripts() {
      ScenePlaybackDetector.DidReloadScripts();
    }

It seems that it can't find InitializeOnLoad and DidReloadScripts. I'm wandering if I still missing something in Unity dependance or anything else, I'm pretty new to it.

**Comment by Shadsa** [comment]
So, so far I have identify 2 matter that explain all the issues above : 

- Concerning the whole UniRx, imported from .unitypackage both from git or Unity AS, there is an issue where some subpart of UniRx are not found (Trigger for example.). So many example provide with doesn't even build without any modification. Under Visual (Visual Editor, not the builded version), UniRx is well-detected, but with some missing part. 
- UniRx.Async as a standalone doesn't have any matching or import matter, but share an issue with the whole UniRx package : under Visual Editor, everythings fine, but when I switch under the builded version for editing work before launching on HoloLens, UniRx and UniRx.Async are both not load : they are marked as "Unresolved", but without more information.

So if I can't make direct source match with the project it explain DLL issue.

I keep up digging the reason and keep you inform. If you already have an idea please let me know. As I said, I'm pretty new to Unity, and so it could probably be a dumb mistake from my part.

**Comment by Shadsa** [comment]
Okay, so it appear to be a compatibility with my Unity version : I'm using 2017.4 and it lack the UI for the packet manager (and I don't want to bother me with entering hundred dependancy by hand).  And the packet manager is needed for Async feature in UniRx. 

Sorry for the flood @neuecc , and still thanks for your awesome work on this soft.
