### ISSUE TITLE
Error on import UniRx 6.2 unitypackage from last build

### ISSUE THREAD

**Issue by Shadsa** [neuecc/UniRx#331]
Errors :

Assets\Plugins\UniRx\Scripts\Async\UnityAsyncExtensions.Jobs.cs(41,22): error CS0246: The type or namespace name 'JobHandle' could not be found (are you missing a using directive or an assembly reference?)

Assets\Plugins\UniRx\Scripts\Async\UnityAsyncExtensions.Jobs.cs(48,37): error CS0246: The type or namespace name 'JobHandle' could not be found (are you missing a using directive or an assembly reference?)

Assets\Plugins\UniRx\Scripts\Async\UnityAsyncExtensions.Jobs.cs(30,51): error CS0246: The type or namespace name 'JobHandle' could not be found (are you missing a using directive or an assembly reference?)

[...] few more of the same type, and then the one wich give all the explanation : 

Assets\Plugins\UniRx\Scripts\Async\UnityAsyncExtensions.Jobs.cs(6,13): error CS0234: The type or namespace name 'Jobs' does not exist in the namespace 'Unity' (are you missing an assembly reference?)

Those errors only appear when I try an Unity build. Those errors doesn't appear when I'm coding in Editor mod, and for Visual Studio everything is fine. I have check all the file ("UnityAsyncExtensions.Jobs") and everything is clean in for VS. 

Any clue about why Unity go wild on ?

**Comment by neuecc** [comment]
Thank you for reporting.
Could you show your Unity version?

**Comment by Shadsa** [comment]
My unity version is 2018.2.0f2, freshly install from Unity hub. 

The same goes for the version in unity store, but not on same classes. But it was all about assembly reference not found or namescpace not correctly identified in Unity (and only at build-time)

**Comment by neuecc** [comment]
Hmn, Unity 2018.02, maybe includes Unity.Jobs...
https://docs.unity3d.com/2018.２/Documentation/ScriptReference/Unity.Jobs.JobHandle.html

maybe `ENABLE_MANAGED_JOBS` symbol is enable/disable Unity Jobs so I'll add this if definition.

**Comment by Shadsa** [comment]
Yeah it seems because VS doesn't see a matter. Well at least I still can't use UniRx due to the Incremental Compiler : it broke down the entire HoloLens bundle and nothing compile after. By any miracle, do you see any workaround that could make Async work without having the compiler in Unity package ?

Thanks for your time @neuecc

**Comment by neuecc** [comment]
solvde in https://github.com/Cysharp/UniTask/issues/4
