### ISSUE TITLE
UniTask.WhenAll crash to desktop on IL2CPP Mac build under certain circumstances 

### ISSUE THREAD

**Issue by zvinless** [neuecc/UniRx#349]
I'm guessing this has to do with IL2CPP internals rather than something specific to UniRx, but I was _not_ able to reproduce using `System.Threading.Tasks.Task` and `System.Threading.Tasks.Task.WhenAll`. It also does not occur on Mono builds.

Circumstances that I've discovered (see code example):
* `WhenAll` params must be of type `UniTask<GenericType<T>>` (2 levels of generic)
* Must specify at least 3 params to `WhenAll` (no crash if there are fewer; I had one project where I had to specify 4 or more, though 😞)
* The body of the function that returns the `UniTask<GenericType<T>>` must actually `await` something

Here is a minimal example:
```csharp
using UnityEngine;
using UniRx.Async;

public class TestScript : MonoBehaviour
{
	class TestType<T> { }

	async UniTask<TestType<T>> DoAsync<T>()
	{
		await UniTask.Delay(200);
		return null;
	}

	void Start()
	{
		UniTask.WhenAll(
			DoAsync<int>(),
			DoAsync<int>(),
			DoAsync<int>()
		).Forget();
	}
}
```

and here is log output when starting the build:
```
Initialize engine version: 2018.2.8f1 (ae1180820377)
GfxDevice: creating device client; threaded=1
2018-09-16 11:35:02.276 whenall[76953:1728803] Color LCD preferred device: NVIDIA GeForce GT 750M (high power)
2018-09-16 11:35:02.276 whenall[76953:1728803] Metal devices available: 2
2018-09-16 11:35:02.276 whenall[76953:1728803] 0: Intel Iris Pro Graphics (low power)
2018-09-16 11:35:02.276 whenall[76953:1728803] 1: NVIDIA GeForce GT 750M (high power)
2018-09-16 11:35:02.276 whenall[76953:1728803] Using device NVIDIA GeForce GT 750M (high power)
Initializing Metal device caps: NVIDIA GeForce GT 750M
UnloadTime: 0.887572 ms
Assertion failed: (klass), function Init, file /Applications/Unity/Hub/Editor/2018.2.8f1/Unity.app/Contents/il2cpp/libil2cpp/vm/Class.cpp, line 1462.
```

I've reproduced on Unity 2018.2.8f1 w/ the Incremental Compiler  0.0.42 preview 21 and on Unity 2018.3.0b1.

Also, thank you neuecc for this library!

**Comment by neuecc** [comment]
Thanks, I should investigate it.

**Comment by zvinless** [comment]
Just heard back from Unity that the cause is [this issue](https://issuetracker.unity3d.com/issues/il2cpp-async-operation-causes-nullreferenceexception-in-the-build-when-scripting-backend-is-il2cpp) which will be fixed soon! Closing 😄
