### ISSUE TITLE
use UniRx(UniRx.Async) with Entities(Unity ECS)

### ISSUE THREAD

**Issue by neuecc** [neuecc/UniRx#354]
workaround.

set following code after `RuntimeInitializeLoadType.BeforeSceneLoad`.

```csharp
// get ECS PlayerLoop
var playerLoop = ScriptBehaviourUpdateOrder.CurrentPlayerLoop;

// set to UniRx.Async PlayerLoop
PlayerLoopHelper.Initialize(ref playerLoop);
```

refer: http://notargs.hateblo.jp/entry/ecs_unirx

**Comment by RDeluxe** [comment]
Shoudn't this be part of the Readme for now ?

**Comment by neuecc** [comment]
solved in https://github.com/Cysharp/UniTask/issues/6
