### ISSUE TITLE
Unity IncrementalCompiler is deprecated

### ISSUE THREAD

**Issue by 5argon** [neuecc/UniRx#372]
In `UniRx.Async` section there is a mention to install IncrementalCompiler. It should add that in 2018.3 the built in compiler is better than IncrementalCompiler.

https://forum.unity.com/threads/unity-incremental-c-compiler-deprecated.523993/page-9#post-3984814

**Comment by Ethan-VisualVocal** [comment]
I can confirm that the UniRx.Async library builds and runs just fine in 2018.3.2f1 w/ IL2CPP output to an iOS device, without the Incremental Compiler package. (I didn't try any earlier versions.)

**Comment by neuecc** [comment]
solved in https://github.com/Cysharp/UniTask/issues/9
