### ISSUE TITLE
await IEnumerator does not work?

### ISSUE THREAD

**Issue by housei** [neuecc/UniRx#381]
Environment
　Unity2018.3.0f2
　UniRx 6.2.2

```csharp
using System.Collections;
using UniRx.Async;
using UnityEngine;

public class TestTest : MonoBehaviour
{
    async void Start()
    {
        await Test();
    }

    IEnumerator Test()
    {
        for (int i = 0; i < 10; i++)
        {
           // It will not stop for 3 seconds...
            yield return new WaitForSeconds(3.0f);
            Debug.Log(i);
        }
    }
}
```

await IEnumerator does not work?

**Comment by miketheprogrammer** [comment]
Make sure you are using the C# upgrades
Unity supports async/await from 2017 with C# upgrades, UniRx provides more lightweight, more powerful async/await integration with Unity. Please see UniRx.Async section.

probably the 4.x

**Comment by neuecc** [comment]
solved in https://github.com/Cysharp/UniTask/issues/11
