### ISSUE TITLE
Force stream to block?

### ISSUE THREAD

**Issue by jwvanderbeck** [neuecc/UniRx#391]
I know this probably sounds silly, but I have a series of async methods implemented using UniRx that all return an observable stream.  This works great, but unfortunately now I need to expose these to an external API that doesn't know anything about UniRx or streams, and requires the calls be synchronous.

In other words I need a way to wrap one of my streams up in such a way that an external API can call it as a normal synchronous method and I have no idea how to do that.

**Comment by jwvanderbeck** [comment]
I found, I think, an example of doing this in standard C# Rx, but it doesn't appear to work with UniRx.

`// Returns the first element of an observable sequence.string result = await observable.FirstAsync();
`

**Comment by BenjaminMoore** [comment]
UniRx supports custom awaiters, then just write
```csharp
string result = await observable.First();
```

**Comment by jwvanderbeck** [comment]
Would it be possible to show an example? Nothing I've tried seems to actually wait on the stream to return a value.
