### ISSUE TITLE
Alloc and performance

### ISSUE THREAD

**Issue by dimmduh** [neuecc/UniRx#395]
Hi!

Was curious about uniRx but checked profiler and omg(
Does everyone have the same allocation and time for set value for IntReactiveProperty ?
(tested in editor 2018.3.8f1
![image](https://user-images.githubusercontent.com/446814/54603922-81797200-4a80-11e9-9471-100e7c1034b9.png)

**Comment by FodderMK** [comment]
I ran a test where I dispose/subscribe to an IntReactiveProperty on every frame and change the value of that reactive property every frame.  I'm seeing 208 bytes of garbage and all of my times are all 0.  Granted the times are impacted by the computer so this isn't an apples-to-apples comparison but the garbage should be relatively consistent.  This was with Unity 2018.3.11f1.

![Annotation 2019-04-01 182304](https://user-images.githubusercontent.com/1096012/55369399-45480780-54ab-11e9-97ae-5514717f3545.png)

**Comment by dimmduh** [comment]
Thx for test. I tested deeper and found the problem in my code.
But I have small alloc (by uniRx) when subscribe, than almost no allocation
