### ISSUE TITLE
Cast ReactiveCollection<T> to to ReactiveCollection<object>

### ISSUE THREAD

**Issue by PhilippCh** [neuecc/UniRx#402]
Maybe I'm missing something here, but is it not possible to cast a ReactiveCollection while still retaining it's original observers on value changes?

What I'd like to do is cast a `ReactiveCollection<T>` to `ReactiveCollection<object>` because I have some general utility classes (that can't use generics) that need to access any ReactiveCollection as a generic `ReactiveCollection<object>`. When the original collection changes, I want my reference to the cast collection to receive updates as well.

**Comment by FodderMK** [comment]
Pretty sure this is a c# limitation as you can't cast generic lists to `List<object>` either.

You could try casting the events you are about and passing those in as IObservable<object>:

```myCollection.ObserveAdd().Select(v => (object)v.Value);```

**Comment by PhilippCh** [comment]
Thanks, after some further research I figured as much. 
In the end, I created a wrapper class that takes any ReactiveCollection during initialization, adds event listeners on ObserveAdd and ObserveRemove and pipes the elements through to another ReactiveCollection<object> that I can then use to add listeners from my other classes.
