### ISSUE TITLE
MissingReferenceException when use ReactiveCollection<T>.ObserveAdd().Subscribe()

### ISSUE THREAD

**Issue by sericaer** [neuecc/UniRx#403]
I use the ReactiveCollection<T>.ObserveAdd().Subscribe() in Start() in script which as Component of a prefab.

There is no problem when the prefab Instantiate first time. 
then the gameObject destroy, and Instantiate second time, Unity report MissingReferenceException:

"MissingReferenceException: The object of type 'XXXX' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object."

**Comment by FodderMK** [comment]
Are you disposing the subscription when the GameObject is destroyed?

**Comment by sericaer** [comment]
Thanks a lot, I use TakeUntilDestroy solve this problem.
