### ISSUE TITLE
How to merge two ReactiveProperty?

### ISSUE THREAD

**Issue by sericaer** [neuecc/UniRx#412]
I have two ReactiveProperty and the operation is same in their Subscribe.
how to merge two ReactiveProperty, then they only use one Subscribe?

**Comment by elhimp** [comment]
Reactive property is still IObservable, so you can use just like any other observable
`Observable.Merge(rp1, rp2)...`

Or if you want single rp out of multiple sources
`Observable.Merge(source1, source2).ToReadOnlyReactiveProperty()...`

Or if you want something other, than just bashing two data streams together, you can use any other combinating method
`CombineLatest, Zip, SelectMany etc.`

**Comment by sericaer** [comment]
Thanks a lot!
