### ISSUE TITLE
.unitypackage 7.0.0 is not the same in Github and Asset Store

### ISSUE THREAD

**Issue by MartinGonzalez** [neuecc/UniRx#413]
Hi there! Just to let you know. I've just downloaded the .unitypackage from `releases` here in Github and seems to be missing some things.

![image](https://user-images.githubusercontent.com/4130008/59268952-38bafa80-8c24-11e9-86aa-67f5a5461635.png)

The UniRx.Async .asmdef and a prefab that is being used in the Sample Todo scene.

The one in Asset store seems to be fine! :D

**Comment by neuecc** [comment]
I confirm it, fix soon.

**Comment by neuecc** [comment]
I've released `7.1.0`(asset store not yet), it is fixed.
