### ISSUE TITLE
OnPointerDownAsObservable(this MonoBehavior...), not UIBehavior.

### ISSUE THREAD

**Issue by cwharris** [neuecc/UniRx#415]
Currently, all pointer-centric extension methods operate on `UIBehavior`.

However, assuming the `Camera` has a `PhysicsRaycaster` component attached, any `MonoBehavior` with a corresponding `Collider` is capable of receiving pointer-centric events, such as `OnPointerDown`, `OnPointerUp`, `OnPointerClick`, `OnDragBegin`, `OnDrag`, `OnDragEnd`.

*These events different from Mouse-centric events*, because the UI layer is able to intercept pointer events before they reach `GameObject`s. This means if I click on a button which happens to be located over a collider, that collider will not receive pointer down/up/click events, but *would* receive mouse down/up/click events.

Assertion: Pointer-centric extension methods should be updated to operate on `MonoBehavior`, not just `UIBehavior`.

**Comment by elhimp** [comment]
Few days ago I've thinked about starting pretty same topic, after few hours that it take me to understand that OnMouse...Triggers are actually representation of old OnMouse functions. Yep, I'm not very clever.

But, beautyfull part is: it easy to just extend unirx a little bit more, and add few more things, if needed.
` private static T GetOrAddTrigger<T>(Collider collider) 
        where T: Component {
            if (collider == null || collider.gameObject == null) return default(T);
            return collider.gameObject.GetComponent<T>() ?? collider.gameObject.AddComponent<T>();
        }


        //KEY FEATURES
        public static IObservable<PointerEventData> OnPointerDownAsObservable(this Collider collider) =>
            GetOrAddTrigger<ObservablePointerDownTrigger>(collider)
            ?.  OnPointerDownAsObservable()
            ??  Observable.Empty<PointerEventData>();


        public static IObservable<PointerEventData> OnPointerEnterAsObservable(this Collider collider) =>...`

**Comment by tylkomat** [comment]
The same can be already achieved with adding trigger components.
```c#
using UniRx;
using UniRx.Triggers;
public class PointerDownHandler: MonoBehaviour {
  void Start() {
    ObservablePointerDownTrigger trigger = gameObject.addComponent<ObservablePointerDownTrigger>();
    IObservable<PointerEventData> observable = trigger.OnPointerDownAsObservable();
    observable.Subscribe(data => Debug.Log("Pointer down " + data));
    ...
  }
}
```

**Comment by cwharris** [comment]
@tylkomat the point is that you'd have to do that for every game object.

@elhimp I didn't realize ObserservableTriggerExtensions was a partial! Nice for organization, but it's still preferable to fix it at the source, IMO.

**Comment by tylkomat** [comment]
@cwharris Of cource, every game object may behave differently to that event. Yes it is one line more than for the "build in" solution. Or you do everything in one line then it is the same.
