### ISSUE TITLE
How to auto trigger ObserveCountChanged when Scene Start?

### ISSUE THREAD

**Issue by sericaer** [neuecc/UniRx#416]
I want check the child MonoBehaviour (panelDetail) is need acitve by listUsed. ObserveCountChanged, when the parent MonoBehaviour Start.

But  ObserveCountChanged is trgger when listUsed changed,  I write a panel.gameObject.SetActive  outter ObserveCountChanged.
 
How to auto trigger ObserveCountChanged when Scene Start, so panel.gameObject.SetActive  which outter ObserveCountChanged can be delete?

   void Start()
    {
        var panel = GetComponentInChildren<panelDetail>();
        panel.gameObject.SetActive(listUsed.Count != 0);

        listUsed.ObserveCountChanged().Subscribe(x =>
        {
            panel.gameObject.SetActive(x != 0);
        });
    }

**Comment by elhimp** [comment]
AFAIK you can use kind of "get initial count" arg 
`listUsed.ObserveCountChanged(true)`
And if it doesn't helf, there always .StartWith operator
`listUsed.ObserveCountChanged().StartWith(listUsed.Count)`

**Comment by sericaer** [comment]
thanks a lot!
