### ISSUE TITLE
UniRx causing build issues

### ISSUE THREAD

**Issue by davidsavage** [neuecc/UniRx#421]
I'm suddenly seeing 41 build errors when using UniRx. For example,

/Assets/Plugins/UniRx/Scripts/UnityEngineBridge/ReactivePropertyReusablePromise.cs(56,56): Error CS0246: The type or namespace name 'IAwaiter<>' could not be found (are you missing a using directive or an assembly reference?) (CS0246)

**Comment by neuecc** [comment]
Currently `ReactivePropertyReusablePromise` does not exists in package.
Probably, old files exist.
Delete it and re-import clearly.

**Comment by davidsavage** [comment]
Thanks Yoshifumi. Working again now.
