### ISSUE TITLE
UPM support

### ISSUE THREAD

**Issue by starikcetin** [neuecc/UniRx#427]
Can we introduce UPM support to be used with https://github.com/mob-sakai/UpmGitExtension? I can do that for you if you don't have time.

**Comment by starikcetin** [comment]
I made it. It is working: https://github.com/starikcetin/UniRx

If you give me an orphan branch named `upm` I can send a pull request.

**Comment by FreakTheMighty** [comment]
@starikcetin how does a release work? Is it an automated flow, or are you branching then moving files manually?

**Comment by starikcetin** [comment]
There is no releasing. The system tracks git refs. So when you make a UPM branch and make a commit there, it is basically a new release.

For organizing the files, there is no need for copy-paste or moving stuff around. Take a look here: https://github.com/starikcetin/awesome-upm#how-to-support-upm-in-my-git-repository

**Comment by MartinGonzalez** [comment]
Please merge!

**Comment by shiena** [comment]
You can use path query parameter from unity2019.3.4f1 and unity2020.1a21.
https://forum.unity.com/threads/some-feedback-on-package-manager-git-support.743345/#post-5425311
