### ISSUE TITLE
Can I use UniRx outisde of Unity, in standalone library for tests?

### ISSUE THREAD

**Issue by mkrzaczek** [neuecc/UniRx#428]
As in the title. I want to create a DLL (.NET library) and use it outside of Unity. The potential use cases are unit testing and using this library on a backend server, without Unity.
Is this something that is supported out of the box? Or can I at least make it work without too much hassle? 
Thanks!

**Comment by zhuxianzhiniko** [comment]
Https://github.com/dotnet/reactive Use this library.

Most of them are consistent with the API.

**Comment by mkrzaczek** [comment]
@zhuxianzhiniko thank you for your answer. Since you suggested using another library - are you saying that I can't use UniRx outside of Unity? I would rather stick to UniRx if I can.

**Comment by zhuxianzhiniko** [comment]
> @zhuxianzhiniko thank you for your answer. Since you suggested using another library - are you saying that I can't use UniRx outside of Unity? I would rather stick to UniRx if I can.

UniRx has some APIs based on Unity's Coroutine that cannot be run in non-Unity environments.

**Comment by mkrzaczek** [comment]
Thank you, I know everything I wanted.
