### ISSUE TITLE
the new unirx PostWWW is giving error

### ISSUE THREAD

**Issue by badoet** [neuecc/UniRx#43]
in unity 4.6, this line : var contentHeaders = (Hash)(object)content.headers;
in the ObservableWWW.cs is throwing casting error

i need to change it to something like this to get it to work : 
 Hash contentHeaders = new Hash();
            if(content.headers != null){
                foreach (DictionaryEntry pair in content.headers)
                {
                    contentHeaders[pair.Key.ToString()] = pair.Value.ToString();
                }
            }    

is this intended? or did i do something wrong?

**Comment by neuecc** [comment]
Today accepted ver 4.7 on UnityAssetStore.
This fix was including.
