### ISSUE TITLE
Property setter rules ignored

### ISSUE THREAD

**Issue by RobertBrunhage** [neuecc/UniRx#434]
I am trying to limit so my health doesn't go below 0, this is what I've done so far.

```
    [SerializeField] private IntReactiveProperty health = new IntReactiveProperty(MaxHealth);
    public IntReactiveProperty Health
    {
        get => health;
        set
        {
            health = value;
            Debug.Log(value.Value);
            if (health.Value < 0)
            {
                health.Value = 0;
            }
        }
    }

    public void TakeDamage(int amount)
    {
        Health.Value -= amount;
        Debug.Log($"You took {amount} damage and has {Health} health left");
    }
```

It seems like the property is not used when using the Health.Value. Is there a simpler way to do this kind of logic or am I missing a crucial step here? As of now the health can still go below 0.

**Comment by jmprimeau** [comment]
Hi,
  The getter and setter sets the reactive property itself whereas the takeDamage fn sets the Value property of an existing reactive property.

Do something like this:

IntReactiveProperty HealthObservable = new IntReactiveProperty(0);

Public int Health {
  Get => HeathObservable.Value;
   Set {
     If(value > 0)
        HeatheObservable.Value = value;
    }}

Simplest thing, you could also look at using commands to validate input.  Not an expert on that though.

Cheers
Jean-Marc

**Comment by RobertBrunhage** [comment]
Hello @jmprimeau, thanks for the answer!

The problem with that would be then my getter is of type int and I can't subscribe to it in another class.

**Comment by jmprimeau** [comment]
Right but then you have two methodes.
Int Health { get; set; }
And
IReadOnlyRP<int> HealthIObservable { get }

Use health to set and have it looking clean with no .Value everywhere.

But that’s basically it, you just always do
X prop {get; set;}
IRORP<X> propObservable { get; }

Jean-Marc

**Comment by RobertBrunhage** [comment]
But I can't set a ReadOnlyReactiveProperty, except in the initialization or am I missing something?

And I also want it to be Serializeable as I am using a scriptable object.

**Comment by jmprimeau** [comment]
Correct, you would set this at construction time or at initialization.
Here is a sample from my project

`  public abstract class EffortBasedLevel<DEFINITION> where DEFINITION:IEffortBasedLeveledDefinition
  {
    public DEFINITION Definition { get; protected set; }

// straight accessor for Effort; supports get and set while hiding the observable implementation
// This is the field that would get serialized...
    public long Effort { get => EffortObservable.Value; set => EffortObservable.Value = value; }
    public ReactiveProperty<long> EffortObservable { get; protected set; }
    public long Level => LevelObservable.Value;
    public IReadOnlyReactiveProperty<long> LevelObservable { get; protected set; }
    public static long LevelFromEffort(double currentEffort, double baseEffort, double researchEffortIncrease, long maxLevels) ...

    public static long EffortFromLevel(int level, double baseEffort, double researchEffortIncrease) ...
    public virtual void Initialize(DEFINITION definition)
    {
      Definition = definition;
      EffortObservable = new ReactiveProperty<long>(0);
      LevelObservable = EffortObservable.Select(accumulatedEffort => LevelFromEffort(accumulatedEffort,Definition.BaseNextLevelEffort,Definition.NextLevelEffortIncrease, Definition.MaxLevels) ).ToReadOnlyReactiveProperty();
    }
  }`

So here, I'm doing basically what I described above.
I have effort and level; effort can be set through the Effort property and Level is derived from Effort.
Both have straight accessors and both have observables.

Now, to your point, the ReactiveProperties are set only once in the Initialize() method.
I haven't tackled serialization yet in this project, but I'm thinking that only the straight accessors will be marked as Serialized; the observable ones will have to come back from Initialize or the constructor.  Probably more from the ctor as the deserializer will probably need the objects to be initialized.

This is a simple example, but I'm doing this pattern at scale in this project and it seems to be working out.

**Comment by RobertBrunhage** [comment]
I see your point and tried implementing it like the following. It works great but still don't really understand what you mean on the serialization part. Properties can't be serialized for the inspector or can they?

```
public IntReactiveProperty healthObservable { get; private set; } = new IntReactiveProperty(MaxHealth);
    public int Health
    {
        get => healthObservable.Value;
        set => healthObservable.Value = value;
    }
```

**Comment by qipa** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在忙碌中，无法亲自回复您的邮件，之后将尽快给您回复。
