### ISSUE TITLE
Scheduler.ThreadPool on webgl

### ISSUE THREAD

**Issue by Ejstn** [neuecc/UniRx#437]
I have following code that does work in editor, on android but doesnt work on webgl:

        Observable.Interval(TimeSpan.FromSeconds(startNewAnimEverySeconds), Scheduler.ThreadPool)
            .ObserveOnMainThread()
            .Subscribe(l => {
                var newAnimState = Random.Range(minAnimIndex, maxAnimIndex + 1);
                Debug.Log("new anim state " + newAnimState.ToString() );
                animator.SetInteger(State, newAnimState);
            }).AddTo(gameObject);

My debug log is not printed to console on webgl, and neither is any error thrown. If i don't specify scheduler - everything works. I am not sure if this is expected for webgl

**Comment by zhuxianzhiniko** [comment]
webgl does not support multithreading. 
Scheduler.ThreadPool cannot be used.

**Comment by Ejstn** [comment]
I had no idea, ok, thx
