### ISSUE TITLE
does not compiled UniRx on 2019.3.12f1

### ISSUE THREAD

**Issue by jungmoona** [neuecc/UniRx#454]
Unity : 2019.3.12f1
UniRx version : download and import today, 2020.5.2

excuse me sir
did you doing test?
2019.3.12f1  does not compiled

only  2019.3.12f1 version

i have UniRX compile test  
2019.2.13f1 -> success
2019.3.12f1 -> fail
2020.2.0a9  -> success

why does not compiled  on 2019.3.12f1 ?

**Comment by KAW0** [comment]
Error message?

**Comment by jungmoona** [comment]
![image](https://user-images.githubusercontent.com/1295849/80854590-4b8f5100-8c74-11ea-81fe-95c5de24561b.png)

error message : "type or namespace name could not be found"

**Comment by KAW0** [comment]
I meant error message in Unity.

**Comment by jungmoona** [comment]
@KAW0 not found error at unity, only vstudio displayed error msg like that

**Comment by KAW0** [comment]
In that case, why don't you write about it right away?
This is not a problem with UniRx. Other libraries in the plugins folder with assebly definition file are not available in Assembly-CSharp. This is probably an bug with the generation of projects in unity so you should report it to Unity Technologies.

**Comment by KAW0** [comment]
https://forum.unity.com/threads/2019-3-12f1-visual-studio-2019-problem.879724/

**Comment by jungmoona** [comment]
ok i got solution, ver.2019.3.13f1 has solved.
thanx @KAW0
