### ISSUE TITLE
Observable still runs once before truly disposed

### ISSUE THREAD

**Issue by TigerHix** [neuecc/UniRx#47]
I'm not sure if this is a bug or not, but I did something like this:

        IDisposable dis = Observable.EveryFixedUpdate().Subscribe(l =>
            {
                Debug.Log("Hello world");
            }
        );

And now console is logging "Hello World" continuously. Perfect. Now I dispose it:

        dis.Dispose();
        Debug.Log("Disposed");

The console log is now a bit weird:

...
Hello world
Hello world
Disposed
Hello world

Which means even though I disposed it, it still runs the task once before it truly disposes. Is this a bug or intended?

**Comment by neuecc** [comment]
Sorry for late response.
It's bug!

Before
```csharp
var count = 0L;
while (!cancellationToken.IsCancellationRequested)
{
    yield return new UnityEngine.WaitForFixedUpdate();
    observer.OnNext(count++);
}
```

But  it doesn't check cancellation after yield.
I'll fix to

```csharp
var count = 0L;
while (!cancellationToken.IsCancellationRequested)
{
    yield return new UnityEngine.WaitForFixedUpdate();

    if (cancellationToken.IsCancellationRequested) yield break;
    observer.OnNext(count++);
}
```

Thank you.

**Comment by TigerHix** [comment]
Thanks! I really appreciate it.

**Comment by neuecc** [comment]
Today accepted ver 4.7 on UnityAssetStore.
This fix was including.
