### ISSUE TITLE
Unity warns about OnMouse_ event handlers on Android build

### ISSUE THREAD

**Issue by mikanbako** [neuecc/UniRx#48]
Unity warns OnMouse_ event handlers on Android build. On Unity 4.6.2f1, the following warning is on its console when Unity builds Android application.

> Game scripts or other custom code contains OnMouse_ event handlers. Presence of such handlers  might impact performance on handheld devices.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

I will create a pull request.

**Comment by neuecc** [comment]
Thank you!
I've merged.
