### ISSUE TITLE
How to Unit Test a method with a callback that is an argument?

### ISSUE THREAD

**Issue by kdawg1406** [neuecc/UniRx#50]
We are trying to unit test this method.  See unit test below

public void Login(String userName, String password, Action<HtAccessToken> successCallback, Action<Exception> errorCallback) {
    try {
        ObservableWWW.PostAndGetBytes(OAuthServiceUrl + "/token",
            Encoding.UTF8.GetBytes("grant_type=password&username=" + userName + "&password=" + password))
                        .Subscribe(x => {
                            try {
                                String response = Encoding.UTF8.GetString(x);
                                var message = JsonConvert.DeserializeObject<HtAccessTokenMessage>(response);
                                var obj = HtAccessTokenMapper.Map(message);
                                successCallback(obj);
                            } catch (Exception ex) {
                                errorCallback(ex);
                            }
                        }, errorCallback);
    } catch (Exception ex) {
        errorCallback(ex);
    }
}

[TestFixture]
public class SecurityServiceTest {

This is our test method.  No matter what we've tried, when running this test using Unity Unit Test Runner, it always fails because the Assert runs (after waiting 10 seconds) and then the method code runs.

How can we test the above method?

Thank you,

Karl

    [Test]
    public void Login_IntegrationTest() {
        // arrange
        var service = new SecurityService();
        String token = String.Empty;
        Exception exception = null;
        // act
        service.Login("user", "password", r => {
            token = r.AccessToken;
        }, ex => {
            exception = ex;
        });

        // assert

        Assert.That(token.Length > 0, Is.True.After(10000));

    }

}

**Comment by neuecc** [comment]
`ObservableWWW.PostAndGetBytes` is in coroutine.
NUnit's DelayedConstraint use `Thread.Sleep`.
So `.After` can't test coroutine.

Maybe Unity Test Tools isn't support coroutine test.
(In the first place Unity does not support start of the coroutine on the editor, UniRx can run coroutine on editor but it's hack)
(So the test on the editor will be impossible, test on the playing scene may be possible)

**Comment by kdawg1406** [comment]
I solved this by putting all code that calls a coroutine into its own class, the in the unit test, the using Substitute to mock out the call to the coroutine.

All all my unit tests working, no problem.

Thank you,

Karl
