### ISSUE TITLE
Extension method in UniRx.ObservableExtensions conflict with System.Reactive

### ISSUE THREAD

**Issue by tangx246** [neuecc/UniRx#510]
In Unity 2021.2.12 (and also happening on 2022.1.0b8), the extension methods in `ObservableExtensions` are conflicting with the extension methods pulled in by `System.Reactive`.

Various error messages along the lines of: ```The call is ambiguous between the following methods or properties: 'UniRx.ObservableExtensions.Subscribe<T>(System.IObservable<T>)' and 'System.ObservableExtensions.Subscribe<T>(System.IObservable<T>)'``` are now appearing whenever there is the `using UniRx; using System;` appearing in the same file.

Is there a suggested workaround / solution to this issue?

**Comment by mwnDK1402** [comment]
I'm running into this exact issue as well. Tried upgrading to 2021.2, but I don't think that's compatible with UniRx for this reason.

**Comment by Nezz** [comment]
I opened a ticket with Unity about this.

**Comment by peterdijkstra** [comment]
I have removed all `using System;` lines in files where this broke, and just changed `IDisposable` to `System.Disposable` etc. That also works, but might be a hassle if you use UniRx a ton

**Comment by mwnDK1402** [comment]
> I have removed all `using System;` lines in files where this broke, and just changed `IDisposable` to `System.IDisposable` etc. That also works, but might be a hassle if you use UniRx a ton
> 
> For what it's worth, this wasn't a problem with 2021.2.8

Yeah, that would be +200 files in our project. I'm not confident this issue will really be fixed. Is this repository completely abandoned?

**Comment by Nezz** [comment]
It's not an issue in UniRx, it's an issue with Unity. Unity 2021.2.12 started referencing System.Reactive.Core for Editor assemblies, most likely as a side-effect of this fix:
> Editor: Fixed an issue where there was no automatic filter out and ignore assemblies that were automatic included as a part of the system library references. ([1363463](https://issuetracker.unity3d.com/issues/compiler-error-cs0433-in-console-when-compiling-using-types-from-the-system-dot-memory-namespace-under-net-standard-2-dot-1))

Because this assembly is not referenced by player assemblies, we can't just put `#if UNITY_2021_2_OR_NEWER` around the duplicate UniRx implementation. There are two possible solutions:
1. Reference System.Reactive.Core in both player and editor assemblies and add `#if UNITY_2021_2_OR_NEWER` to UniRx.
2. Restore the Unity 2021.2.11 behaviour and not reference System.Reactive.Core in any of the assemblies

Note that if you are targeting the full .NET with your app, System.Reactive.Core might get referenced by player assemblies too and the first approach might work for you already. However, for those like us who target .NET Standard this is not a solution.

**Comment by Nomad404** [comment]
A workaround for this can be
`using UniRxExt = UniRx.ObservableExtensions;`

and then use that as a prefix for and UniRx related calls like 
`UniRxExt.Subscribe(...);`

**Comment by tangx246** [comment]
System.Reactive.Core is not automatically available to player assemblies at build time, so we can't just use System.Reactive in our code without pulling it in separately

**Comment by Joycraft** [comment]
A workaround for this can be 
rename `SystemsRx.MicroRx.Extensions.IObservableExtensions.Subscribe()`

**Comment by Pixellore** [comment]
I have similar problem, and I went hard way of renaming the UniRx extension method's names. Which kinda works on Windows platform, but when I try to build for the other platforms such as PS4 or Switch etc, it complains that it is missing the System.Reactive.Core (or not allowed)...

I am using Unity 2021.2.12f1 and full .net targeting.

Any idea? I mean, for windows build, I can see System.Reactive.Core.dll being included in the build...?

**Comment by neuecc** [comment]
I've tried on Unity 2021.2.13f1.
API Compatibillity Level: .NET Standard 2.1 is worked.
API Compatibillity Level: .NET Framework, conflicts.

Indeed, it implicitly refers to `System.Reactive.*.dll`.
I think it's a bug in Unity, so until there's an official announcement (references added, etc.), I'll wait and see.

**Comment by Nezz** [comment]
This is the latest I got:
>The devs have informed me that this looks like unintended behaviour but they will need to investigate the problem further.

**Comment by Pixellore** [comment]
> This is the latest I got:
> 
> > The devs have informed me that this looks like unintended behaviour but they will need to investigate the problem further.

"The devs" => Do you mean from Unity? Any links to the forum thread?

**Comment by Nezz** [comment]
Yes, from Unity. This is from enterprise support (not public).

**Comment by quabug** [comment]
A quick workaround of this issue should be put `using UniRx` into `namespace`.
``` c#
namespace Game
{
    using UniRx;
    ...
}
```

For those code without `namespace` you have to remove `using System` as @peterdijkstra suggested.

**Comment by parkycai** [comment]
Still broken in 2021.2.15f1, keep staying in 2021.2.11f1

**Comment by Nezz** [comment]
Some news:
>The devs have decided to explicitly exclude System.Reactive.* assemblies from our .NET 4.8 profile. The pull request for this change is now awaiting approval.
>
>In the meantime, it appears you can work around the problem by additionally targeting a runtime platform for the affected assembly definitions (e.g. Editor AND Stadia, if you're not deploying on the Stadia platform, this should have no effect on the project).

**Comment by scho** [comment]
I've just checked out 2021.2.17f1. This issue is still in this version.

**Comment by superkerokero** [comment]
> A quick workaround of this issue would be put `using UniRx` into `namespace`.
> 
> ```cs
> namespace Game
> {
>     using UniRx;
>     ...
> }
> ```
> 
> For those code without `namespace` you have to remove `using System` as @peterdijkstra suggested.

This works.
If you happen to be using `using System;` as well, put it outside of the namespace, then you can use it as normal:

```c#
using System;

namespace SomeNamaspace {
    using UniRx;

    ...
}

```

**Comment by scho** [comment]
It's still the same in 2021.2.18f1.

**Comment by n00levoy** [comment]
Still not fixed in 2021.2.19f1.

**Comment by scho** [comment]
2021.3.0f1 is out - but this issue is still not fixed. 
@Nezz: Any news from your source?

**Comment by Nezz** [comment]
It's fixed internally on Unity's trunk and is awaiting backport to the 2021.3 branch. I requested an update earlier today on when the backport will be happening.

**Comment by scho** [comment]
I've just checked with `2021.3.1f1`, it's still not fixed!

**Comment by fernandodarci** [comment]
Really, 2021.3.1f1 it´s still the problem.
But I think if UniRx is a plugin, the right way is the plugin dev adapt it to Unity, not the other way.
UniRx can be a popular plugin, but Unity is for those that use and don´t use this plugin.
So I think that the plugin need to be adapted, since the people that use System.ObservableExtensions don´t lose this tool already in main tool.

**Comment by fernandodarci** [comment]
I shifted all instances of Subscribe to RxSubscribe in UniRx.ObservableExtensions and the code. Problem solved.
Just a tip. Produce code with prefixes, it guarantee that no conflicts happen.

**Comment by Nezz** [comment]
There is no need for these methods in UniRx if System.Reactive is referenced, since it replicates the same extension methods. The issue is that System.Reactive is referenced only sometimes (Editor assemblies).

**Comment by kLy** [comment]
Hey so it isn't in 2021.3.1? :( Is the backport still happening? 

Nezz, there is still no response from Unity? Any link for us to track this backport? Or is this just a PM exchange you're having with Unity?

**Comment by n00levoy** [comment]
This [issue](https://issuetracker.unity3d.com/issues/ambiguous-method-error-when-asmdef-only-targets-editor) was mentioned in Unity 2022.2a release notes.

**Comment by scho** [comment]
@kLy: The [issue](https://issuetracker.unity3d.com/issues/ambiguous-method-error-when-asmdef-only-targets-editor) mentions, that it will be fixed in 2021.3:

> Fixed in 2022.2.X
> Fix In Review for 2021.3.X, 2022.1.X

**Comment by ZhouKes** [comment]
2021.3.2, it's still not fixed!

**Comment by Nezz** [comment]
The PR for the backport was submitted yesterday for 2021.3. If all goes well, it should be merged and released fairly quickly.

**Comment by kLy** [comment]
Oooh now the page says: 

Fixed in: 2021.3.3f1
Fixed in: ​​​​​​​2022.1.1f1

:)

**Comment by cpetry** [comment]
Great!
Is 2021.3.3f released yet? Then I'll jump over

**Comment by tangx246** [comment]
A really preliminary test on 2022.1.1f seems to show that it's fixed. I'm just going to assume that it now works and close this issue

**Comment by Nezz** [comment]
2021.3.3 is not out yet, but hopefully it'll be out soon - it was scheduled for this week.

**Comment by kLy** [comment]
Woohoo! 2021.3.3 just released! https://unity3d.com/unity/whats-new/2021.3.3

And it includes the fix:
- Scripting: Removed outdated System.Reactive extensions from .Net 4.8 profile. (1407597)

Tested on my project. Working! :D

**Comment by ZhouKes** [comment]
Yesterday I installed 2021.3.3 via UnityHub on one computer, but today I am on another computer and cannot find this version.

**Comment by momijijin** [comment]
my unity editor version is 2022.1.0b16，when i switch to il2cpp + .net standard2.1(pc platform), this compilation error disappears
