### ISSUE TITLE
Switchmap equivalent?

### ISSUE THREAD

**Issue by arnotes** [neuecc/UniRx#525]
I was wondering if this library has a switchmap equivalent?
https://rxjs.dev/api/operators/switchMap

I tried `ContinueWith` but it doesnt seem to create cancellations

**Comment by yujuiting** [comment]
I am also looking for SwitchMap.
Do you get any solution?

**Comment by arnotes** [comment]
> I am also looking for SwitchMap. Do you get any solution?

@yujuiting I ended up using this code
```cs
obs1.Select(x => obs2).Switch()
```

**Comment by Thaina** [comment]
Maybe this would work?

```C#
object lastListen = null;
observable.SelectMany((id) => {
	lastListen = anotherObserver;
	return anotherObserver.TakeWhile((_) => current == lastListen);
});
```
