### ISSUE TITLE
ReactiveCollections - The name 'Items' does not exist in the current context

### ISSUE THREAD

**Issue by FodderMK** [neuecc/UniRx#53]
When my Unity build target is set to `Web Player` I see the following error being thrown by UniRx:

```
CompilerError: The name `Items' does not exist in the current context

StackTrace:
Compiler CompilerError
    Assets/UniRx/Scripts/UnityEngineBridge/ReactiveCollection.cs: line 123 column 25
```

It appears that the `Web Player` build target is using a modified version of `Connection<T>` that does not have the `Items` property.  My temporary workaround is to surround the `ReactiveCollection<T>` and `ReactiveCollectionExtensions` classes with `#if !UNITY_WEBPLAYER`.

Unity 5.0.0f4, UniRx master branch.

**Comment by neuecc** [comment]
Thank you!
I didn't know its problem.

I've fixed, update to AssetStore soon.

**Comment by neuecc** [comment]
ver 4.7.2 released at March 27th 2015.
