### ISSUE TITLE
Does not "When" call completed method in "Subscribe" ?

### ISSUE THREAD

**Issue by hotmiyacchi** [neuecc/UniRx#57]
Hi there,
I'm quite impressed to use UniRx and trying things these days.

Let me ask a question that I couldn't get "complete" at this code.
        Observable.EveryUpdate()
            .Where(x => x < 10)
            .Subscribe(x => Debug.Log(x),
                    ex => Debug.LogError(ex.Message),
                () => Debug.Log("completed"));

Does not "When" call completed method in "Subscribe" ?

**Comment by neuecc** [comment]
Observable.EveryUpdate is an infinite sequence generator and Where is only filter.
For example, if sequence returns 10 or less again, Where throughout the value again.

```csharp
// 0,1,2,3,4,5,6,7,8,9,-10,-11,-12,-13,....,
Observable.EveryUpdate()
    .Select(x => (x >= 10) ? -x : x)
    .Where(x => x < 10);
```

If you want to stop sequence, you can use `Observable.TakeWhile`.

```csharp
Observable.EveryUpdate()
    .TakeWhile(x => x < 10)
    .Subscribe(x => Debug.Log(x), ex => Debug.LogError(ex.Message), () => Debug.Log("completed"));
```

See: Intro to Rx's Reducing a sequence section.
http://www.introtorx.com/content/v1.0.10621.0/05_Filtering.html

**Comment by hotmiyacchi** [comment]
Thanks a lot for your perfect response!

I really appreciate for your work.
