### ISSUE TITLE
UNITY_IPHONE and Mouse observable triggers

### ISSUE THREAD

**Issue by danien** [neuecc/UniRx#60]
Unity now allows *Mouse methods even on mobile (e.g., when UNITY_IPHONE is defined) as touches are mapped to these methods. Can the UNITY_IPHONE conditional guards around the *Mouse Observable triggers be removed?

* Also, UNITY_IPHONE is deprecated in favor or UNITY_IOS but might be a good idea to use both for now for legacy user code.

**Comment by neuecc** [comment]
Thank you!
I've removed conditional guards.

**Comment by neuecc** [comment]
Ah, sorry, in build time unity logs warning

```
Game scripts or other custom code contains OnMouse_ event handlers. Presence of such handlers might impact performance on handheld devices.
UnityEditor.HostView:OnGUI()
```

I want to reduce warning by UniRx so revive conditional guard.
