### ISSUE TITLE
ObservableStateMachine Trigger makes stop animating

### ISSUE THREAD

**Issue by cruwel** [neuecc/UniRx#70]
I'm huge fan of UniRx. I'm very glad to feedback to this library project.
in this time I report a bug with ObservableStateMachine trigger 
but it's not actually UniRx's problem. it seems unity's bug.

currently, version 5.0.1, 5.0.2(current latest) of unity has bugs that make stop animating of animator
callback is works, but animation clip isn't playing.
on using callbacks like belows

```
using UnityEngine;
using System.Collections;

public class StateMachineBehaviourInheritance : StateMachineBehaviour {

	public override void OnStateMove (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
	{
		base.OnStateMove (animator, stateInfo, layerIndex);
		Debug.Log ("Move Called");
	}
}
```

so in UniRx.
https://github.com/neuecc/UniRx/blob/master/Assets/UniRx/Scripts/UnityEngineBridge/Triggers/ObservableStateMachineTrigger.cs#L84

I can't use this trigger script with animator. because this script stopping animation playing. 
cause of OnStateMove has been used.
I already reported this problem to unity.

but at least, in version of unity ~5.0.2, excepting this events on trigger is better I consider.

I can send you project files that I send to unity if you want.
but the bug is easy to be reproduced I consider.

thanks for great library.

**Comment by neuecc** [comment]
Thank you! and sorry for late response.

I confirmed in Unity 5.1.0 f3.
Your suggestion is right, I've comment out `OnStateMove`.
If your report is accepted to Unity and this problem will be fixed,
please tell me the result.

**Comment by cruwel** [comment]
Thanks for your response.

In this time I checked out this bug out on Unity 5.1.2 p3 but it still not fixed.
and this report is tracking by unity corp on url belows

http://fogbugz.unity3d.com/default.asp?700990_9jqaim4ev33i8e9h

Best regards
ruel

**Comment by Garfeild** [comment]
Hi there,

Unity replied on this issue (in case you missed it) :)

P.S. Thanks for UniRx!

**Comment by neuecc** [comment]
Thanks!
I've commented on source code.
