### ISSUE TITLE
ReactiveProperty is not initialized with certain value.

### ISSUE THREAD

**Issue by naito7** [neuecc/UniRx#72]
If I use ReactiveProperty with initial value and the value is default(T),
it seems ReactiveProperty is not initialized correctly.

            var t0 = Observable.Never<int>()
                .ToReactiveProperty(0); // canPublishValueOnSubscribe is still false
            var t1 = Observable.Never<int>()
                .ToReactiveProperty(1); // canPublishValueOnSubscribe becomes true

            t0.Subscribe(a => Debug.LogFormat("s0 : OnNext {0}", a), (Exception e) => Debug.LogFormat("s0 : OnError : {0}", e), () => Debug.LogFormat("s0 : OnCompleted"));
            t1.Subscribe(a => Debug.LogFormat("s1 : OnNext {0}", a), (Exception e) => Debug.LogFormat("s1 : OnError : {0}", e), () => Debug.LogFormat("s1 : OnCompleted"));

Result is only
s1 : OnNext 1

Original version ReactiveProperty doesn't have this issue.

            var t0 = Observable.Never<int>()
                .ToReactiveProperty(0);
            var t1 = Observable.Never<int>()
                .ToReactiveProperty(1);

            t0.Subscribe(a => Console.WriteLine("s0 : OnNext {0}", a), (Exception e) => Console.WriteLine("s0 : OnError : {0}", e), () => Console.WriteLine("s0 : OnCompleted"));
            t1.Subscribe(a => Console.WriteLine("s1 : OnNext {0}", a), (Exception e) => Console.WriteLine("s1 : OnError : {0}", e), () => Console.WriteLine("s1 : OnCompleted"));

s0 : OnNext 0
s1 : OnNext 1

Is this expected behavior?

Thanks,

**Comment by neuecc** [comment]
Thank you.
No, it's bug.

I fixed related issue at https://github.com/neuecc/UniRx/commit/f1c28bec9700330f0cb1b042d8d9947dc0a66b2e
This fix solves this issue, too.

**Comment by naito7** [comment]
Thanks a lot!

I tested f1c28be and the issue was fixed.
