### ISSUE TITLE
Unity4.6 raises exception on multithreading

### ISSUE THREAD

**Issue by pokehanai** [neuecc/UniRx#73]
Unity4.6 raises exception with the code below:
```cs
Observable.Create<Unit>(observer => {
	observer.OnCompleted();
	return Disposable.Empty;
})
.SubscribeOn(Scheduler.ThreadPool)
.ObserveOn(Scheduler.MainThread)
.Subscribe();
```

```
CompareBaseObjectsInternal can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
```

It occurs at  MainThreadDispatcher.cs#L181
```cs
            var dispatcher = Instance;
            if (dispatcher != null)    // here
```

The reason is that since the `dispatcher` instance is a Unity component, `!=` invokes `UnityEngine.Object.operator !=` (then it violates the main-thread-restriction).

A workaround could be replacing that kind of lines with like
```cs
            if (!object.ReferenceEquals(dispatcher, null))
```

In Unity5.1, I did not see this issue(at least with the same sample code).

**Comment by neuecc** [comment]
Thank you!
I enbug at  release 4.8.1, It's my mistake.
I've pushed fix code.
