### ISSUE TITLE
Cannot find map function

### ISSUE THREAD

**Issue by olpie101** [neuecc/UniRx#79]
Hello,
 I am trying to perform several map functions on a collider on the `OnTriggerEnterAsObservable()` methods. I am trying to something like this:

```C#
this.OnTriggerEnterAsObservable()
	.map(colldr => /*read mesh from file here, return mesh object*/)
	.filter(mesh => /*previous map may return null so filter*/)
	.Subscribe(mesh => /*set new mesh as game object's current mesh*/);
```

is this possible?

**Comment by neuecc** [comment]
map -> `Select`, filtrer -> `Where`, flatMap -> `SelectMany`.

See operator reference http://reactivex.io/documentation/operators/filter.html
UniRx same with RxNET.

**Comment by olpie101** [comment]
Thank you
