### ISSUE TITLE
AsyncSubject.OnCompleted(), completing IObserver twice

### ISSUE THREAD

**Issue by j6lim** [neuecc/UniRx#80]
I am a big fan of UniRx. While I was reading the source code I found this.

https://github.com/neuecc/UniRx/blob/master/Assets/UniRx/Scripts/Subjects/AsyncSubject.cs#L56-L66

It calls old.OnCompleted() twice, which seems to be redundant.

**Comment by neuecc** [comment]
Thank you!
Yes, I've merged.
