### ISSUE TITLE
Runtime error trying to change Dictionary for ObservableWWW.Post form.

### ISSUE THREAD

**Issue by huminado** [neuecc/UniRx#82]
Posted this on uFrame MVVM forums, but it seems like a possible issue for UniRx.  I don't see how to remove the "Authorization" hashtable member so when the dictionary merge takes place it won't barf.

Here's copy/paste from my uFrame MVVM and original thread: https://invertgamestudios.com/chat/startcoroutine-from-viewmodel

So possibly this is my fault. Or a bug in UniRX. No idea. But the corrolary to this code using a hashtable was running fine before trying to switch to UniRX. It doesn't want to allow changing the "Authorization" header field.

When I try to run this code (which compiles fine, the url is set to "localhost:3000" but it gave same error even with canned "www.google.com" ):

    public static Dictionary<k, v=""> HashtableToDictionary<k, v="">(Hashtable table)
    {
        return table
            .Cast<dictionaryentry>()
                .ToDictionary(kvp => (K)kvp.Key, kvp => (V)kvp.Value);
    }
    void doLogin( string username, string pw, UserViewModel viewModel )
    {
        string url      =   viewModel.serverURL + "/some/route" ;

        WWWForm form = new WWWForm();

        Dictionary<string, string=""> headers = HashtableToDictionary<string, string="">(form.headers);

        byte[] rawData = form.data;

        form.AddField("bogusname", "bogusvalue");

        string  usernameAndPassword     =   username+":"+pw;
        headers["Authorization"] = "Basic " + System.Convert.ToBase64String(System.Text.Encoding.ASCII.GetBytes( usernameAndPassword ));

        ObservableWWW.Post(url, form, headers, null )
        .Subscribe(
            x => Debug.Log(x.Substring(0, 100)), // onSuccess
            ex => Debug.LogException(ex)); // onError
...
I get a runtime error upon calling it:

ArgumentException: An element with the same key already exists in the dictionary. System.Collections.Generic.Dictionary2[System.String,System.String].Add (System.String key, System.String value) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404) UniRx.ObservableWWW.MergeHash (System.Collections.Hashtable wwwFormHeaders, System.Collections.Generic.Dictionary2 externalHeaders) (at Assets/uFrame/MVVM/UniRx/Scripts/UnityEngineBridge/ObservableWWW.cs:135) UniRx.ObservableWWW+cAnonStorey19A.<>m234 (IObserver1 observer, UniRx.CancellationToken cancellation) (at Assets/uFrame/MVVM/UniRx/Scripts/UnityEngineBridge/ObservableWWW.cs:53) UniRx.Observable+<fromcoroutine>c__AnonStorey15E1[System.String].<>m116 (IObserver1 observer) (at Assets/uFrame/MVVM/UniRx/Scripts/UnityEngineBridge/Observable.Unity.cs:211) UniRx.Observable+AnonymousObservable1+cAnonStorey178[System.String].<>m_205 () (at Assets/uFrame/MVVM/UniRx/Scripts/Observable.Creation.cs:42) UniRx.InternalUtil.ScheduledItem.Invoke () (at Assets/uFrame/MVVM/UniRx/Scripts/InternalUtil/ScheduledItem.cs:44) UniRx.Scheduler+CurrentThreadScheduler+Trampoline.Run (UniRx.InternalUtil.SchedulerQueue queue) (at Assets/uFrame/MVVM/UniRx/Scripts/Schedulers/CurrentThreadScheduler.cs:122) UniRx.Scheduler+CurrentThreadScheduler.Schedule (TimeSpan dueTime, System.Action action) (at Assets/uFrame/MVVM/UniRx/Scripts/Schedulers/CurrentThreadScheduler.cs:91) UniRx.Scheduler+CurrentThreadScheduler.Schedule (System.Action action) (at Assets/uFrame/MVVM/UniRx/Scripts/Schedulers/CurrentThreadScheduler.cs:69) UniRx.Observable+AnonymousObservable1[System.String].Subscribe (IObserver1 observer) (at Assets/uFrame/MVVM/UniRx/Scripts/Observable.Creation.cs:42) UniRx.ObservableExtensions.Subscribe[String] (IObservable1 source, System.Action1 onNext, System.Action1 onError) (at Assets/uFrame/MVVM/UniRx/Scripts/Observer.cs:163) RESTapiMVVM.UserController.RESTgetUserAuthToken (System.String username, System.String pw, RESTapiMVVM.UserViewModel viewModel) (at Assets/_MVVMrepository/RESTapi/Controllers/UserController.cs:52) RESTapiMVVM.UserController.login (RESTapiMVVM.UserViewModel viewModel) (at Assets/_MVVMrepository/RESTapi/Controllers/UserController.cs:25) RESTapiMVVM.UserControllerBase.loginHandler (RESTapiMVVM.loginCommand command) (at Assets/_MVVMrepository/RESTapi/Controllers.designer.cs:77) uFrame.MVVM.Signal1[RESTapiMVVM.loginCommand].OnNext (RESTapiMVVM.loginCommand value) (at Assets/uFrame/MVVM/Framework/MVVM/ViewModels/Signal.cs:46) RESTapiMVVM.LoginScreenBase.Executelogin () (at Assets/MVVMrepository/RESTapi/Views.designer.cs:101) UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) UnityEngine.Events.UnityEvent.Invoke () UnityEngine.UI.Button.Press () (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:35) UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:44) UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:52) UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:269) UnityEngine.EventSystems.EventSystem:Update()

**Comment by huminado** [comment]
Since I'm brand new to UniRX - is there a work around for this issue which still allows posting with credentials in the header?

**Comment by huminado** [comment]
From uFrame Slack channel:

aahz [8:46 PM] 
ahh, didn't check if it was readonly, then the only way I guess is to change the unirx code in ObservableWWW.cs, line 126-138 or so, to use index operator instead of .Add()

frankbraker [8:48 PM] 
i'll stick with the unity -- really not interested in UniRX at all.

aahz [8:48 PM] 
and I meant behind the scenes, what happens when you do ObservableWWW.Post(), it goes to merge the header data of the form with the extra headers arg, so stack goes ObservableWWW.Post() -> .Fetch() -> .MergeHash(), and inside the .MergeHash() is where the argument exception comes from

aahz [8:50 PM]
so the only lines you need to change are the 2 that say newHeaders.Add(whatever) to `newHeaders[item.Key.ToString()] = item.Value.ToString();` (edited)

aahz [8:51 PM]
then you should be able to use the same code in the unirx issue without getting the arg exception

**Comment by neuecc** [comment]
Sorry for late response and thanks for very useful information.

Oh, I missed it at specified version.
https://github.com/neuecc/UniRx/blob/master/Assets/UniRx/Scripts/UnityEngineBridge/ObservableWWW.cs#L125-L152
Thanks, I'll fix it.
