### ISSUE TITLE
question about avoiding GC

### ISSUE THREAD

**Issue by qiankanglai** [neuecc/UniRx#84]
In `Observable.Unity.cs`, may I create a `WaitForFixedUpdate`/`WaitForEndOfFrame` instance at first, and use it repeat to avoid allocation in runtime?

https://github.com/neuecc/UniRx/blob/fc0b7e6ec3087215469af7bc9a1a52837c32f4bb/Assets/UniRx/Scripts/UnityEngineBridge/Observable.Unity.cs#L24
https://github.com/neuecc/UniRx/blob/fc0b7e6ec3087215469af7bc9a1a52837c32f4bb/Assets/UniRx/Scripts/UnityEngineBridge/Observable.Unity.cs#L26

**Comment by neuecc** [comment]
I didn't know is it safe cache WaitForFixedUpate.
But maybe it's safe, http://stackoverflow.com/questions/26160377/can-i-cache-waitforendofframe-or-should-i-use-yield-new-everytime
I'll change it, use cached WaitForFixedUpdate and WaitForEndOfFrame.
Thank you!

**Comment by qiankanglai** [comment]
In my experiments, after changing the code works well.
After this tiny modification, my game can run with zero GC if user has no interaction :smile: 

Thanks for your great work
