### ISSUE TITLE
A small mistake？

### ISSUE THREAD

**Issue by CoderMin** [neuecc/UniRx#90]
at：UniRx/Assets/UniRx/Scripts/Observable.Paging.cs  line:434

nextSpan += timeShift;
Whether it should be:
nextSpan += timeSpan;

**Comment by CoderMin** [comment]
and
at: UniRx/Assets/UniRx/Scripts/Disposables/ScheduledDisposable.cs  line:40

if (Interlocked.Increment(ref isDisposed) == 0)
Whether it should be:
if (Interlocked.Increment(ref isDisposed) == 1)

**Comment by CoderMin** [comment]
at:  UniRx/Assets/UniRx/Scripts/Subjects/ReplaySubject.cs
line:63
startTime = scheduler.Now;
line:68
var elapsedTime = Scheduler.Normalize(scheduler.Now - startTime);
line:126
queue.Enqueue(new TimeInterval<T>(value, Scheduler.Now - startTime));// "Scheduler.Now" whether it should be "scheduler.Now"

**Comment by neuecc** [comment]
Thanks, I'll check soon!

**Comment by neuecc** [comment]
ReplaySubject and ScheduledDisposable was fixed, thank you.
Discussing about Observable.Paging move to #96
