### ISSUE TITLE
Multiline StringReactiveProperty

### ISSUE THREAD

**Issue by lostfictions** [neuecc/UniRx#91]
Is there anyway to have a StringReactiveProperty that appears as multiline (as if it had had the `[Multiline]` attribute applied to it) in the inspector?

The only way to do it that I can see would be to add a new concrete implementation of `ReactiveProperty<T>` that duplicates most of its code, but that doesn't seem like a very good idea.

**Comment by neuecc** [comment]
Thank you for suggestion.

I've added `MultilineReactivePropertyAttribute` for StringReactiveProperty.
You can use

```csharp
public StringReactiveProperty SinglelineString;

[MultilineReactiveProperty]
public StringReactiveProperty MultineString;
```

![image](https://cloud.githubusercontent.com/assets/46207/11302788/b37f1342-8fe2-11e5-88e0-65b25b8c6743.png)

Is it OK?

**Comment by lostfictions** [comment]
That's great! Thank you!
