### ISSUE TITLE
Is there PublishSubject implementation available?

### ISSUE THREAD

**Issue by AAverin** [neuecc/UniRx#93]
Is there PublishSubject implementation available?

**Comment by neuecc** [comment]
Thank you for great suggestion!
I didn't know PublishSubject because it is not available in Rx.NET.

It seems useful, I'll implement it!

**Comment by AAverin** [comment]
I'm trying to port my RxBus implementation from Java to Unity. The idea is to have a Subject that will observer and send same Event objects, it should be thread safe and it should not send old Events to new subscribers - thus PublishSubject.

Another thing I noticed missing - a thread safe subject. In RxJava it's called SerializedSubject. Not sure if it makes sence in .Net and Unity environment.

**Comment by neuecc** [comment]
Sorry for late response.

At first, `PublishSubject` of RxJava same as `Subject` of UniRx.

RxJava's SerializedSubject is slightly complex.
Here is simple, cheapy version.

```csharp
public sealed class SerializedSubject<T> : ISubject<T>
{
    readonly ISubject<T> actual;
    readonly object gate = new object();

    public SerializedSubject(ISubject<T> actual)
    {
        this.actual = actual;
    }

    public void OnNext(T value)
    {
        lock (gate)
        {
            actual.OnNext(value);
        }
    }

    public void OnError(Exception error)
    {
        lock (gate)
        {
            actual.OnError(error);
        }
    }

    public void OnCompleted()
    {
        lock (gate)
        {
            actual.OnCompleted();
        }
    }

    public IDisposable Subscribe(IObserver<T> observer)
    {
        lock (gate)
        {
            return actual.Subscribe(observer);
        }
    }
}
```

**Comment by neuecc** [comment]
5.2.0 includes ISubject.Synchronize().
